import { ExternalLink, FolderKanban } from "lucide-react";
import { useRoute } from "wouter";
import { trpc } from "@/lib/trpc";

export default function PublicPortfolio() {
  const [, params] = useRoute("/portfolio/:handle");
  const handle = params?.handle?.toLowerCase() ?? "";
  const portfolio = trpc.pathpilot.portfolio.public.useQuery({ handle }, { enabled: Boolean(handle) });

  if (portfolio.isLoading) return <main className="min-h-screen bg-slate-50 px-5 py-12 text-slate-950 dark:bg-background dark:text-foreground"><div className="mx-auto max-w-3xl"><p className="eyebrow">PathPilot portfolio</p><div className="mt-4 h-9 w-56 bg-slate-200 dark:bg-slate-800" /><div className="mt-3 h-4 max-w-xl bg-slate-100 dark:bg-slate-900" /></div></main>;
  if (!portfolio.data) return <main className="min-h-screen bg-slate-50 px-5 py-16 text-slate-950 dark:bg-background dark:text-foreground"><section className="mx-auto max-w-xl border border-slate-200 bg-card p-6 text-card-foreground dark:border-slate-700"><FolderKanban className="size-5 text-primary" /><h1 className="mt-4 text-xl font-semibold">Portfolio unavailable</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">This public portfolio does not exist or currently has no published projects.</p></section></main>;

  const { profile, projects } = portfolio.data;
  return <main className="min-h-screen bg-slate-50 text-slate-950 dark:bg-background dark:text-foreground"><header className="border-b border-slate-200 bg-card dark:border-slate-700"><div className="mx-auto flex max-w-4xl items-center gap-2 px-5 py-4"><span className="grid size-7 place-items-center bg-slate-950 text-xs font-bold text-white dark:bg-slate-100 dark:text-slate-950">P</span><span className="text-sm font-semibold tracking-[-0.03em]">PathPilot portfolio</span></div></header><section className="mx-auto max-w-4xl px-5 py-10"><p className="eyebrow">Student work</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">{profile.displayName}</h1>{profile.introduction && <p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{profile.introduction}</p>}<p className="mt-4 text-xs text-muted-foreground">This page contains only projects the student chose to publish. It does not show private project notes, scope, milestones, progress, planning activity, simulations, mentor content, or recommendations.</p><div className="mt-8 grid gap-4 md:grid-cols-2">{projects.map(project => <article key={project.id} className="border border-slate-200 bg-card p-5 text-card-foreground dark:border-slate-700"><h2 className="text-lg font-semibold">{project.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{project.summary}</p>{project.technologies.length > 0 && <div className="mt-4 flex flex-wrap gap-1">{project.technologies.map(item => <span key={item} className="status-tag">{item}</span>)}</div>}<div className="mt-5 flex flex-wrap gap-3">{project.repositoryUrl && <a className="utility-link" href={project.repositoryUrl} target="_blank" rel="noreferrer">Repository <ExternalLink className="size-3.5" /></a>}{project.liveUrl && <a className="utility-link" href={project.liveUrl} target="_blank" rel="noreferrer">Live project <ExternalLink className="size-3.5" /></a>}</div></article>)}</div></section></main>;
}
