import { Brand } from "@/components/Brand";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Printer, ShieldCheck } from "lucide-react";
import { useRoute } from "wouter";

export default function SharedPlanningReport() {
  const [, params] = useRoute("/share/:token");
  const token = params?.token ?? "";
  const report = trpc.pathpilot.sharedReport.get.useQuery({ token }, { enabled: Boolean(token) });
  if (report.isLoading) return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950 dark:bg-background dark:text-foreground"><div className="mx-auto max-w-3xl surface-panel p-6 text-sm text-muted-foreground">Loading the shared planning report…</div></main>;
  if (report.error || !report.data) return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950 dark:bg-background dark:text-foreground"><div className="mx-auto max-w-3xl surface-panel p-6"><Brand /><h1 className="mt-8 text-2xl font-semibold tracking-[-0.04em]">This report link is unavailable.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">It may have expired, been revoked, or been entered incorrectly. Ask the student to create a new private link if they still want to share this report.</p></div></main>;
  const value = report.data;
  const metrics = [{ label: "Goals", value: `${value.goals.completed}/${value.goals.total}`, detail: `${value.goals.active} active` }, { label: "Projects", value: `${value.projects.completed}/${value.projects.total}`, detail: `${value.projects.active} active` }, { label: "Roadmap", value: value.roadmap.exists ? `${value.roadmap.completionPercentage}%` : "Not started", detail: value.roadmap.exists ? `${value.roadmap.completed}/${value.roadmap.total} milestones complete` : "No active roadmap" }, { label: "Visible activity", value: String(value.visibleActivityCount), detail: "recent planning actions" }];
  return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950 dark:bg-background dark:text-foreground"><article className="mx-auto max-w-3xl surface-panel overflow-hidden"><header className="flex flex-col justify-between gap-4 border-b border-slate-200 px-5 py-5 sm:flex-row sm:items-start dark:border-slate-700"><div><Brand /><p className="eyebrow mt-7">Private shared snapshot</p><h1 className="mt-2 text-2xl font-semibold tracking-[-0.04em]">Planning report</h1><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">A student has chosen to share this limited snapshot of saved planning progress.</p></div><Button size="sm" variant="outline" className="gap-2" onClick={() => window.print()}><Printer className="size-3.5" />Print</Button></header><div className="grid divide-y divide-slate-200 sm:grid-cols-2 sm:divide-x sm:divide-y-0 dark:divide-slate-700">{metrics.map(metric => <section key={metric.label} className="p-5"><p className="text-xs text-muted-foreground">{metric.label}</p><p className="data-value mt-1 text-xl font-semibold">{metric.value}</p><p className="mt-1 text-xs text-muted-foreground">{metric.detail}</p></section>)}</div><section className="border-t border-slate-200 px-5 py-5 dark:border-slate-700"><p className="text-xs font-medium text-muted-foreground">Current focus</p><h2 className="mt-2 text-lg font-semibold">{value.focus.title}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{value.focus.detail}</p></section><footer className="border-t border-slate-200 px-5 py-4 dark:border-slate-700"><div className="flex gap-2"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" /><p className="text-xs leading-5 text-muted-foreground">{value.privacyNote}</p></div></footer></article></main>;
}
