import { createClient } from "@supabase/supabase-js";
import { currentSupabaseClient, getSupabaseConfig } from "./supabase";
import { buildAdaptiveResults, chooseSimulationDecision, getPublicScenario, getSimulationGraph, initialSimulationState } from "./simulation/engine";
import type { BehavioralEvidence, DecisionRecord, SimulationState } from "./simulation/contracts";

export type ResourceLink = { label: string; url: string };
export type CareerRecommendation = { name: string; description: string; salaryRange: string; educationRequirements: string; requiredSkills: string[]; dailyResponsibilities: string[]; relatedCareers: string[]; matchScore: number; reasoning: string; strengths: string[]; missingSkills: string[]; realityCheck: string; nextSteps: string[] };
export type RoadmapMilestoneInput = { year: number; title: string; description?: string; category: "skill" | "project" | "experience"; deadline?: Date; priority: "low" | "medium" | "high"; estimatedHours: number; resources: ResourceLink[]; progress?: number; status?: GoalStatus; sortOrder: number };
type GoalStatus = "not_started" | "in_progress" | "completed" | "paused";

const client = () => currentSupabaseClient();
const list = <T>(value: T[] | null) => value ?? [];
const strings = (value: unknown) => Array.isArray(value) ? value as string[] : [];
const resources = (value: unknown) => Array.isArray(value) ? value as ResourceLink[] : [];
const check = (error: { message: string } | null) => { if (error) throw new Error("We could not save your PathPilot data. Please try again."); };
const date = (value: string | null | undefined) => value ? new Date(value) : null;
const iso = (value?: Date) => value?.toISOString() ?? null;
const slug = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

function serviceClient() {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) throw new Error("Career catalog persistence is not configured.");
  return createClient(getSupabaseConfig().url, key, { auth: { persistSession: false, autoRefreshToken: false } });
}
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function validateCareerCatalogWrite(userId: string, recommendations: CareerRecommendation[]) {
  if (!uuidPattern.test(userId)) throw new Error("A valid authenticated user is required to update career matches.");
  if (recommendations.length !== 5) throw new Error("Career discovery must contain exactly five matches.");
  const names = new Set<string>();
  for (const recommendation of recommendations) {
    const normalizedName = recommendation.name.trim().toLowerCase();
    if (!normalizedName || normalizedName.length > 180 || names.has(normalizedName) || !Number.isInteger(recommendation.matchScore) || recommendation.matchScore < 1 || recommendation.matchScore > 100) throw new Error("Career recommendations failed validation.");
    if (recommendation.requiredSkills.length < 3 || recommendation.requiredSkills.length > 8 || recommendation.dailyResponsibilities.length < 2 || recommendation.dailyResponsibilities.length > 6 || recommendation.relatedCareers.length < 2 || recommendation.relatedCareers.length > 6 || recommendation.strengths.length < 1 || recommendation.strengths.length > 6 || recommendation.missingSkills.length < 1 || recommendation.missingSkills.length > 6 || recommendation.nextSteps.length < 2 || recommendation.nextSteps.length > 5) throw new Error("Career recommendations failed validation.");
    names.add(normalizedName);
  }
}
async function syncSharedCareerCatalog(recommendations: CareerRecommendation[]) {
  const admin = serviceClient();
  const stored: { careerId: string; recommendation: CareerRecommendation }[] = [];
  for (const recommendation of recommendations) {
    const { data, error } = await admin.from("careers").upsert({ slug: slug(recommendation.name), name: recommendation.name, description: recommendation.description, salary_range: recommendation.salaryRange, education_requirements: recommendation.educationRequirements, required_skills: recommendation.requiredSkills, daily_responsibilities: recommendation.dailyResponsibilities, related_careers: recommendation.relatedCareers }, { onConflict: "slug" }).select("id").single();
    check(error); stored.push({ careerId: (data as any).id, recommendation });
  }
  return stored;
}
export function profile(row: any) { return row ? { id: row.id, userId: row.user_id, grade: row.grade, location: row.location, countryCode: row.country_code ?? null, educationSystem: row.education_system ?? null, interests: strings(row.interests), skills: strings(row.skills), activities: strings(row.activities), careerPreferences: strings(row.career_preferences), onboardingCompletedAt: date(row.onboarding_completed_at), createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at) } : null; }
export function onboardingDraft(row: any) { return row ? { currentStep: row.current_step, payload: row.payload as Record<string, unknown> } : null; }
function goal(row: any) { return { id: row.id, userId: row.user_id, title: row.title, description: row.description, category: row.category, deadline: date(row.deadline), priority: row.priority, estimatedHours: row.estimated_hours, resources: resources(row.resources), progress: row.progress, status: row.status as GoalStatus, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at) }; }
function milestone(row: any) { return { id: row.id, roadmapId: row.roadmap_id, year: row.year, title: row.title, description: row.description, category: row.category, deadline: date(row.deadline), priority: row.priority, estimatedHours: row.estimated_hours, resources: resources(row.resources), progress: row.progress, status: row.status as GoalStatus, sortOrder: row.sort_order }; }
function simulation(row: any) { return row ? { id: row.id, userId: row.user_id, career: row.career, title: row.title, scenarios: row.scenarios ?? [], userChoices: row.user_choices ?? [], technicalScore: row.technical_score ?? 0, leadershipScore: row.leadership_score ?? 0, careerCompatibilityScore: row.career_compatibility_score ?? 0, score: row.score ?? 0, feedback: row.feedback, status: row.status, completedAt: date(row.completed_at), createdAt: new Date(row.created_at), updatedAt: date(row.updated_at) ?? new Date(row.created_at), engineVersion: row.engine_version ?? "legacy-v1", scenarioGraphId: row.scenario_graph_id, currentNodeId: row.current_node_id, nodeHistory: list(row.node_history), decisionHistory: list(row.decision_history), simulationState: row.simulation_state ?? null, behavioralEvidence: list(row.behavioral_evidence), behavioralProfile: row.behavioral_profile ?? null, compatibilityResults: list(row.compatibility_results), resultSummary: row.result_summary ?? null } : undefined; }

export async function getStudentProfile(userId: string) { const { data, error } = await client().from("student_profiles").select("*").eq("user_id", userId).maybeSingle(); check(error); return profile(data); }
export async function getOnboardingDraft(userId: string) { const { data, error } = await client().from("onboarding_drafts").select("*").eq("user_id", userId).maybeSingle(); check(error); return onboardingDraft(data); }
export async function saveOnboardingDraft(userId: string, currentStep: number, payload: Record<string, unknown>) { const { data, error } = await client().from("onboarding_drafts").upsert({ user_id: userId, current_step: currentStep, payload, updated_at: new Date().toISOString() }, { onConflict: "user_id" }).select().single(); check(error); return data; }
export async function saveStudentProfile(userId: string, value: { grade: string; location: string; countryCode?: string | null; educationSystem?: string | null; interests: string[]; skills: string[]; activities: string[]; careerPreferences: string[] }) { const db = client(); const { data, error } = await db.from("student_profiles").upsert({ user_id: userId, grade: value.grade, location: value.location, country_code: value.countryCode ?? null, education_system: value.educationSystem ?? null, interests: value.interests, skills: value.skills, activities: value.activities, career_preferences: value.careerPreferences, onboarding_completed_at: new Date().toISOString(), updated_at: new Date().toISOString() }, { onConflict: "user_id" }).select().single(); check(error); const draft = await db.from("onboarding_drafts").delete().eq("user_id", userId); check(draft.error); return profile(data); }
export async function updateStudentCountryContext(userId: string, countryCode: string, educationSystem: string) { const { data, error } = await client().from("student_profiles").update({ country_code: countryCode, education_system: educationSystem, updated_at: new Date().toISOString() }).eq("user_id", userId).select().maybeSingle(); check(error); if (!data) throw new Error("Student profile not found."); return profile(data); }

export async function getCareerMatches(userId: string) {
  const { data, error } = await client().from("career_matches").select("*, careers(*)").eq("user_id", userId).order("rank"); check(error);
  return list(data as any[]).map(row => ({ id: row.id, rank: row.rank, matchScore: row.match_score, reasoning: row.reasoning, strengths: strings(row.strengths), missingSkills: strings(row.missing_skills), realityCheck: row.reality_check, nextSteps: strings(row.next_steps), generatedAt: new Date(row.generated_at), career: { id: row.careers.id, name: row.careers.name, description: row.careers.description, salaryRange: row.careers.salary_range ?? "Location-dependent", educationRequirements: row.careers.education_requirements ?? "Varies by pathway", requiredSkills: strings(row.careers.required_skills), dailyResponsibilities: strings(row.careers.daily_responsibilities), relatedCareers: strings(row.careers.related_careers) } }));
}
export async function replaceCareerMatches(userId: string, recommendations: CareerRecommendation[]) {
  validateCareerCatalogWrite(userId, recommendations);
  const stored = await syncSharedCareerCatalog(recommendations);
  const db = client();
  const remove = await db.from("career_matches").delete().eq("user_id", userId); check(remove.error);
  const insert = await db.from("career_matches").insert(stored.map(({ careerId, recommendation }, index) => ({ user_id: userId, career_id: careerId, rank: index + 1, match_score: Math.round(recommendation.matchScore), reasoning: recommendation.reasoning, strengths: recommendation.strengths, missing_skills: recommendation.missingSkills, reality_check: recommendation.realityCheck, next_steps: recommendation.nextSteps }))); check(insert.error);
  return getCareerMatches(userId);
}

export async function listGoals(userId: string) { const { data, error } = await client().from("goals").select("*").eq("user_id", userId).order("deadline", { nullsFirst: false }); check(error); return list(data as any[]).map(goal); }
export async function createGoal(userId: string, value: { title: string; description?: string; category: string; deadline?: Date; priority: "low" | "medium" | "high"; estimatedHours: number; resources?: ResourceLink[] }) { const { data, error } = await client().from("goals").insert({ user_id: userId, title: value.title, description: value.description ?? null, category: value.category, deadline: iso(value.deadline), priority: value.priority, estimated_hours: value.estimatedHours, resources: value.resources ?? [] }).select().single(); check(error); return goal(data); }
export async function updateGoal(userId: string, goalId: string, update: { progress?: number; status?: GoalStatus; priority?: "low" | "medium" | "high" }) { const { data, error } = await client().from("goals").update({ ...update, updated_at: new Date().toISOString() }).eq("id", goalId).eq("user_id", userId).select().maybeSingle(); check(error); if (!data) throw new Error("Goal not found."); return goal(data); }

export async function getActiveRoadmap(userId: string) { const { data: roadmap, error } = await client().from("roadmaps").select("*").eq("user_id", userId).eq("status", "active").order("updated_at", { ascending: false }).limit(1).maybeSingle(); check(error); if (!roadmap) return undefined; const { data: milestones, error: milestoneError } = await client().from("roadmap_milestones").select("*").eq("roadmap_id", (roadmap as any).id).order("year").order("sort_order"); check(milestoneError); return { id: (roadmap as any).id, userId: (roadmap as any).user_id, targetCareer: (roadmap as any).target_career, completionPercentage: (roadmap as any).completion_percentage, status: (roadmap as any).status, createdAt: new Date((roadmap as any).created_at), updatedAt: new Date((roadmap as any).updated_at), milestones: list(milestones as any[]).map(milestone) }; }
export async function createRoadmap(userId: string, targetCareer: string, items: RoadmapMilestoneInput[]) { const db = client(); const archive = await db.from("roadmaps").update({ status: "archived", updated_at: new Date().toISOString() }).eq("user_id", userId).eq("status", "active"); check(archive.error); const { data, error } = await db.from("roadmaps").insert({ user_id: userId, target_career: targetCareer }).select().single(); check(error); const inserted = await db.from("roadmap_milestones").insert(items.map(item => ({ roadmap_id: (data as any).id, year: item.year, title: item.title, description: item.description ?? null, category: item.category, deadline: iso(item.deadline), priority: item.priority, estimated_hours: item.estimatedHours, resources: item.resources, progress: item.progress ?? 0, status: item.status ?? "not_started", sort_order: item.sortOrder }))); check(inserted.error); return getActiveRoadmap(userId); }
export async function updateMilestoneProgress(userId: string, milestoneId: string, progress: number) { const db = client(); const { data: item, error } = await db.from("roadmap_milestones").select("*, roadmaps!inner(user_id)").eq("id", milestoneId).eq("roadmaps.user_id", userId).maybeSingle(); check(error); if (!item) throw new Error("Roadmap milestone not found."); const normalized = Math.max(0, Math.min(100, Math.round(progress))); const saved = await db.from("roadmap_milestones").update({ progress: normalized, status: normalized === 100 ? "completed" : normalized > 0 ? "in_progress" : "not_started" }).eq("id", milestoneId); check(saved.error); const { data: all, error: allError } = await db.from("roadmap_milestones").select("progress").eq("roadmap_id", (item as any).roadmap_id); check(allError); const entries = list(all as any[]); const completion = entries.length ? Math.round(entries.reduce((total, entry) => total + Number(entry.progress), 0) / entries.length) : 0; const update = await db.from("roadmaps").update({ completion_percentage: completion, updated_at: new Date().toISOString() }).eq("id", (item as any).roadmap_id).eq("user_id", userId); check(update.error); return getActiveRoadmap(userId); }

export async function createSimulation(userId: string, value: { career: string; title: string; scenarios: unknown[] }) {
  const { data, error } = await client().from("simulations").insert({ user_id: userId, career: value.career, title: value.title, scenarios: value.scenarios, user_choices: [] }).select().single();
  check(error);
  const persisted = simulation(data);
  if (!persisted) throw new Error("Simulation could not be created.");
  return persisted;
}
export async function getSimulation(userId: string, simulationId: string) { const { data, error } = await client().from("simulations").select("*").eq("id", simulationId).eq("user_id", userId).maybeSingle(); check(error); return simulation(data); }
export async function completeSimulation(userId: string, simulationId: string, value: { userChoices: { scenarioId: string; choiceId: string }[]; technicalScore: number; leadershipScore: number; careerCompatibilityScore: number; score: number; feedback: string }) { const { error } = await client().from("simulations").update({ user_choices: value.userChoices, technical_score: value.technicalScore, leadership_score: value.leadershipScore, career_compatibility_score: value.careerCompatibilityScore, score: value.score, feedback: value.feedback, status: "completed", completed_at: new Date().toISOString() }).eq("id", simulationId).eq("user_id", userId); check(error); return getSimulation(userId, simulationId); }

export async function createAdaptiveSimulation(userId: string, career: string) {
  const graph = getSimulationGraph(career); const state = initialSimulationState(graph);
  const { data, error } = await client().from("simulations").insert({ user_id: userId, career, title: graph.title, scenarios: [], user_choices: [], engine_version: "adaptive-v2", scenario_graph_id: graph.id, current_node_id: state.currentNodeId, node_history: [], decision_history: [], simulation_state: state, behavioral_evidence: [] }).select().single();
  check(error); const saved = simulation(data); if (!saved) throw new Error("Simulation could not be created."); return saved;
}
export async function getAdaptiveSimulation(userId: string, simulationId: string) { const { data, error } = await client().from("simulations").select("*").eq("id", simulationId).eq("user_id", userId).eq("engine_version", "adaptive-v2").maybeSingle(); check(error); return simulation(data); }
export async function getResumableAdaptiveSimulation(userId: string) { const { data, error } = await client().from("simulations").select("*").eq("user_id", userId).eq("engine_version", "adaptive-v2").eq("status", "in_progress").order("updated_at", { ascending: false }).limit(1).maybeSingle(); check(error); return simulation(data); }
export async function getLatestCompletedAdaptiveSimulation(userId: string) { const { data, error } = await client().from("simulations").select("*").eq("user_id", userId).eq("engine_version", "adaptive-v2").eq("status", "completed").order("completed_at", { ascending: false }).limit(1).maybeSingle(); check(error); return simulation(data); }
export function getAdaptivePublicScenario(value: NonNullable<Awaited<ReturnType<typeof getAdaptiveSimulation>>>) { if (!value.simulationState || !value.scenarioGraphId) throw new Error("Adaptive simulation state is unavailable."); return getPublicScenario(getSimulationGraph(value.career), value.simulationState as SimulationState); }
export async function chooseAdaptiveSimulationDecision(userId: string, simulationId: string, decisionId: string) {
  const current = await getAdaptiveSimulation(userId, simulationId); if (!current) throw new Error("Simulation not found."); if (current.status !== "in_progress") throw new Error("Simulation is already complete."); if (!current.simulationState) throw new Error("Adaptive simulation state is unavailable.");
  const graph = getSimulationGraph(current.career);
  const transition = chooseSimulationDecision(graph, current.simulationState as SimulationState, decisionId, current.behavioralEvidence as BehavioralEvidence[], current.decisionHistory as DecisionRecord[]);
  const patch: Record<string, unknown> = { current_node_id: transition.state.currentNodeId, node_history: transition.state.previousNodeIds, decision_history: transition.history, simulation_state: transition.state, behavioral_evidence: transition.evidence, user_choices: transition.history.map(item => ({ scenarioId: item.nodeId, choiceId: item.decisionId })), updated_at: new Date().toISOString() };
  if (transition.completed) {
    const matches = await getCareerMatches(userId); const results = buildAdaptiveResults(transition.evidence, matches.map(match => ({ name: match.career.name, matchScore: match.matchScore })));
    const trait = (name: string) => results.behavioralProfile.traits.find(item => item.trait === name)?.score ?? 50;
    patch.status = "completed"; patch.completed_at = new Date().toISOString(); patch.behavioral_profile = results.behavioralProfile; patch.compatibility_results = results.compatibility; patch.result_summary = results.summary; patch.feedback = results.summary; patch.technical_score = Math.round((trait("analytical_thinking") + trait("problem_solving") + trait("systems_thinking") + trait("attention_to_detail")) / 4); patch.leadership_score = Math.round((trait("collaboration") + trait("communication") + trait("ownership")) / 3); patch.career_compatibility_score = results.compatibility[0]?.score ?? 0; patch.score = Math.round(((patch.technical_score as number) + (patch.leadership_score as number) + (patch.career_compatibility_score as number)) / 3);
  }
  const { data, error } = await client().from("simulations").update(patch).eq("id", simulationId).eq("user_id", userId).select().maybeSingle(); check(error); if (!data) throw new Error("Simulation not found."); return simulation(data)!;
}

export async function getOrCreateMentorConversation(userId: string) { const db = client(); const { data: existing, error } = await db.from("ai_conversations").select("*").eq("user_id", userId).order("updated_at", { ascending: false }).limit(1).maybeSingle(); check(error); if (existing) return existing as any; const { data, error: insertError } = await db.from("ai_conversations").insert({ user_id: userId, title: "Career mentor", context: {} }).select().single(); check(insertError); return data as any; }
export async function getConversationMessages(userId: string, conversationId: string) { const { data, error } = await client().from("ai_messages").select("*").eq("conversation_id", conversationId).eq("user_id", userId).order("created_at"); check(error); return list(data as any[]).map(row => ({ id: row.id, conversationId: row.conversation_id, userId: row.user_id, role: row.role as "user" | "assistant", content: row.content, createdAt: new Date(row.created_at) })); }
export async function addMentorMessage(userId: string, conversationId: string, role: "user" | "assistant", content: string) { const db = client(); const message = await db.from("ai_messages").insert({ user_id: userId, conversation_id: conversationId, role, content }); check(message.error); const conversation = await db.from("ai_conversations").update({ updated_at: new Date().toISOString() }).eq("id", conversationId).eq("user_id", userId); check(conversation.error); }
export async function listProjects(userId: string) { const { data, error } = await client().from("projects").select("*, project_goals(goal_id)").eq("user_id", userId).order("updated_at", { ascending: false }); check(error); return list(data as any[]).map(row => ({ id: row.id, userId: row.user_id, name: row.name, description: row.description, skills: strings(row.skills), githubLink: row.github_link, liveUrl: row.live_url, status: row.status, progress: row.progress, startDate: row.start_date, completionDate: row.completion_date, careerId: row.career_id, goalIds: list(row.project_goals).map((link: any) => link.goal_id), createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at) })); }
export async function createProject(userId: string, value: { name: string; description: string; skills: string[]; githubLink?: string; liveUrl?: string; status: "idea" | "in_progress" | "completed" | "archived"; progress: number; startDate?: string; completionDate?: string; careerId?: string; goalIds?: string[] }) { const db = client(); const { data, error } = await db.from("projects").insert({ user_id: userId, name: value.name, description: value.description, skills: value.skills, github_link: value.githubLink ?? null, live_url: value.liveUrl ?? null, status: value.status, progress: value.progress, start_date: value.startDate ?? null, completion_date: value.completionDate ?? null, career_id: value.careerId ?? null }).select().single(); check(error); if (value.goalIds?.length) { const linked = await db.from("project_goals").insert(value.goalIds.map(goalId => ({ project_id: (data as any).id, goal_id: goalId }))); check(linked.error); } return (await listProjects(userId)).find(project => project.id === (data as any).id); }
export async function updateProject(userId: string, projectId: string, value: { status?: "idea" | "in_progress" | "completed" | "archived"; progress?: number; liveUrl?: string | null; githubLink?: string | null; completionDate?: string | null }) { const { data, error } = await client().from("projects").update({ status: value.status, progress: value.progress, live_url: value.liveUrl, github_link: value.githubLink, completion_date: value.completionDate, updated_at: new Date().toISOString() }).eq("id", projectId).eq("user_id", userId).select().maybeSingle(); check(error); if (!data) throw new Error("Project not found."); return data; }
export async function getDashboardData(userId: string) { const [profileValue, matches, goals, roadmap, projects, recentSimulation] = await Promise.all([getStudentProfile(userId), getCareerMatches(userId), listGoals(userId), getActiveRoadmap(userId), listProjects(userId), getLatestCompletedAdaptiveSimulation(userId)]); const activeGoals = goals.filter(item => item.status !== "completed" && item.status !== "paused"); const completedGoals = goals.filter(item => item.status === "completed").length; const simulationSignal = recentSimulation ? Math.min(10, Math.round(recentSimulation.careerCompatibilityScore / 10)) : 0; const readiness = Math.round(Math.min(100, (roadmap?.completionPercentage ?? 0) * 0.45 + (goals.length ? (completedGoals / goals.length) * 20 : 0) + (matches[0]?.matchScore ?? 0) * 0.25 + simulationSignal)); return { profile: profileValue, matches, goals, activeGoals, roadmap, projects, readiness, recentSimulation: recentSimulation ? { id: recentSimulation.id, career: recentSimulation.career, resultSummary: recentSimulation.resultSummary, strongestTraits: recentSimulation.behavioralProfile?.strongestTraits ?? [], completedAt: recentSimulation.completedAt, compatibilityScore: recentSimulation.careerCompatibilityScore } : null }; }
