import { getNationalEducationContext } from "./national-context";

export type RecommendationKind = "primary" | "explore";
export type CareerRecommendationMetadata = {
  kind: RecommendationKind;
  requirementId: string;
  requirementLabel: string;
  studentGap: string;
  tip: string;
  countryContext: string;
  verificationStatus: "general";
  sourceLabel: "General recommendation — verify local availability";
};

export type CareerRequirementAction = {
  id: string;
  kind: RecommendationKind;
  requirementId: string;
  requirementLabel: string;
  category: "skill" | "project" | "experience";
  priority: "low" | "medium" | "high";
  estimatedHours: number;
  coverageTerms: string[];
  title: (context: CareerRecommendationContext) => string;
  description: (context: CareerRecommendationContext) => string;
  gap: (context: CareerRecommendationContext) => string;
  tip: string;
};

export type CareerRecommendationContext = {
  career: string;
  countryCode: string | null | undefined;
  grade: string;
  existingEvidence: string[];
  strongestTraits: string[];
};

const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const gradeNumber = (grade: string) => Number(grade.match(/\d+/)?.[0] ?? 10);
const countryPlanningAction = (context: CareerRecommendationContext, subject: string) => {
  const country = getNationalEducationContext(context.countryCode);
  if (country.code === "US") return `Check your school catalog for the most challenging ${subject} course available and compare it with pathways you are considering.`;
  if (country.code === "IN") return `Map ${subject} preparation to your board subjects and intended higher-education pathway; verify any entrance requirements through official sources.`;
  if (country.code === "GB") return `Compare ${subject} preparation with the entry requirements of UK courses you are considering; verify details with providers or UCAS.`;
  return `Use your local school or provider catalog to identify an appropriate ${subject} preparation step, then verify requirements with the official source.`;
};
const levelAction = (context: CareerRecommendationContext, foundation: string, advanced: string) => gradeNumber(context.grade) >= 11 ? advanced : foundation;

const profiles: Record<string, CareerRequirementAction[]> = {
  "software engineer": [
    { id: "cs-foundation", kind: "primary", requirementId: "software-cs-foundations", requirementLabel: "Computer science foundations", category: "skill", priority: "high", estimatedHours: 16, coverageTerms: ["data structures", "algorithms", "ap computer science", "computer science a"], title: context => `Plan a ${getNationalEducationContext(context.countryCode).label} computer science preparation step`, description: context => countryPlanningAction(context, "computer science and mathematics"), gap: () => "No advanced computer science or algorithms preparation is recorded yet.", tip: "Choose the most rigorous option available to you, then build one small Java, Python, or web project that applies the concepts beyond the assignment." },
    { id: "software-artifact", kind: "primary", requirementId: "software-portfolio-evidence", requirementLabel: "Substantial software artifact", category: "project", priority: "high", estimatedHours: 32, coverageTerms: ["software application", "full stack", "github project", "production app", "web app"], title: context => levelAction(context, "Build a small software application that uses an external API", "Build and document a production-style software application with tests"), description: () => "Define one user problem, a limited first release, version control, a public demo or screenshots, and a README that explains your decisions.", gap: () => "Your saved evidence does not yet show a substantial software artifact tied to a real problem.", tip: "Make the final artifact demonstrable: explain the problem, approach, result, trade-offs, and what you would improve next." },
    { id: "software-collaboration", kind: "primary", requirementId: "software-collaboration", requirementLabel: "Technical collaboration", category: "experience", priority: "medium", estimatedHours: 12, coverageTerms: ["software subsystem", "technical subsystem", "code review", "technical lead", "engineering team"], title: () => "Take ownership of a technical subsystem or reviewable deliverable", description: () => "Use a coding, robotics, or maker activity to plan, build, test, and explain one bounded component with collaborators.", gap: () => "Current activities do not yet document ownership of a technical deliverable with collaboration evidence.", tip: "Ask for a clear subsystem, define acceptance checks, and keep a short decision log so your contribution is visible." },
    { id: "software-interview", kind: "explore", requirementId: "software-career-understanding", requirementLabel: "Career understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["software engineer interview", "developer interview"], title: () => "Interview a software professional about one real development workflow", description: context => `Prepare five questions about debugging, collaboration, review, and delivery; compare what you hear with your simulation observations. ${countryPlanningAction(context, "professional learning and outreach")}`, gap: () => "You have not recorded a direct professional perspective on day-to-day software work.", tip: "Ask for one example of a difficult bug or trade-off, not only general career advice." },
  ],
  "doctor physician": [
    { id: "medicine-science", kind: "primary", requirementId: "medicine-science-foundation", requirementLabel: "Science preparation", category: "skill", priority: "high", estimatedHours: 16, coverageTerms: ["advanced biology", "advanced chemistry", "ap biology", "ap chemistry"], title: () => "Plan an advanced science preparation step where available", description: context => countryPlanningAction(context, "biology, chemistry, and quantitative science"), gap: () => "No advanced science preparation is recorded yet.", tip: "Use a notebook to connect one scientific concept each week to a real health or research question." },
    { id: "medicine-evidence", kind: "primary", requirementId: "medicine-scientific-reasoning", requirementLabel: "Scientific reasoning", category: "project", priority: "high", estimatedHours: 20, coverageTerms: ["science investigation", "biology research", "health research"], title: () => "Complete a science investigation with a documented evidence trail", description: () => "Choose a safe school, community, or open-data question; state a hypothesis, collect or analyze evidence, record limitations, and present a conclusion.", gap: () => "Your saved work does not yet show a documented scientific investigation.", tip: "Keep a research log with your question, method, failed attempts, evidence, and what changed your conclusion." },
    { id: "medicine-exposure", kind: "primary", requirementId: "medicine-healthcare-exposure", requirementLabel: "Ethical healthcare exposure", category: "experience", priority: "medium", estimatedHours: 8, coverageTerms: ["healthcare volunteering", "hospital volunteering", "healthcare exposure"], title: () => "Identify one official healthcare or health-science exposure pathway", description: () => "Use an official school, hospital, clinic, university, or community organization source to review age, safeguarding, eligibility, and supervision requirements before applying.", gap: () => "No verified healthcare or health-science exposure is recorded.", tip: "Never assume access or eligibility; confirm safeguarding and age requirements directly with the organization before committing time." },
    { id: "medicine-interview", kind: "explore", requirementId: "medicine-career-understanding", requirementLabel: "Career understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["physician interview", "doctor interview"], title: () => "Speak with a healthcare professional or educator about clinical teamwork", description: () => "Prepare questions about communication, uncertainty, ethics, and collaborative care; reflect on what the work requires beyond academic preparation.", gap: () => "No direct perspective on healthcare teamwork is recorded.", tip: "Ask about one situation where communication changed a patient or team outcome." },
  ],
  "entrepreneur startup founder": [
    { id: "startup-customer-discovery", kind: "primary", requirementId: "startup-customer-discovery", requirementLabel: "Customer discovery", category: "experience", priority: "high", estimatedHours: 10, coverageTerms: ["customer interviews", "customer discovery", "user interviews"], title: () => "Run five structured customer-discovery conversations", description: () => "Choose a small problem area, write neutral questions, interview potential users, and summarize repeated needs without pitching a solution first.", gap: () => "No structured customer-discovery evidence is recorded.", tip: "Ask about recent behavior and frustrations instead of asking whether someone likes your idea." },
    { id: "startup-validation", kind: "primary", requirementId: "startup-product-validation", requirementLabel: "Product validation", category: "project", priority: "high", estimatedHours: 24, coverageTerms: ["product prototype", "validated prototype", "startup mvp"], title: () => "Build a small prototype and test it with real users", description: () => "Create the smallest useful version of one idea, set one measurable learning goal, collect feedback, and document what you changed after testing.", gap: () => "Your saved work does not yet show a prototype tested against user feedback.", tip: "Define one learning metric before building; revise the prototype after at least one full feedback cycle." },
    { id: "startup-finance", kind: "primary", requirementId: "startup-financial-basics", requirementLabel: "Business-model fundamentals", category: "skill", priority: "medium", estimatedHours: 10, coverageTerms: ["business model", "unit economics", "entrepreneurship course"], title: () => "Create a one-page business-model and cost sketch", description: context => `${countryPlanningAction(context, "business and entrepreneurship learning") } Use a simple model to state the customer, problem, value, costs, and assumptions you still need to test.`, gap: () => "No structured business-model or financial-basics evidence is recorded.", tip: "Treat every number as an assumption until a customer, price, or cost source validates it." },
    { id: "startup-interview", kind: "explore", requirementId: "startup-career-understanding", requirementLabel: "Career understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["founder interview", "entrepreneur interview"], title: () => "Interview a founder about one product decision that changed", description: () => "Ask how they identified a customer problem, what evidence changed their plan, and how they decided what not to build.", gap: () => "No recorded first-hand perspective on iterative entrepreneurship work.", tip: "Focus on decisions and evidence, not only the founder’s final outcome." },
  ],
  "environmental scientist": [
    { id: "environmental-science", kind: "primary", requirementId: "environmental-science-foundation", requirementLabel: "Environmental science foundation", category: "skill", priority: "high", estimatedHours: 14, coverageTerms: ["environmental science", "ecology", "earth science", "gis"], title: () => "Plan an environmental science or data-preparation step", description: context => countryPlanningAction(context, "environmental science, ecology, geography, or data analysis"), gap: () => "No environmental-science or ecological-data preparation is recorded.", tip: "Choose one local or global environmental issue and connect each learning block to the data used to understand it." },
    { id: "environmental-data", kind: "primary", requirementId: "environmental-data-evidence", requirementLabel: "Environmental data investigation", category: "project", priority: "high", estimatedHours: 24, coverageTerms: ["environmental data project", "water quality project", "climate data project", "environmental investigation"], title: () => "Build a local or open-data environmental investigation", description: () => "Frame a measurable question, use a safe official or open dataset where needed, document methods and limitations, and communicate one evidence-based finding.", gap: () => "Your saved work does not yet show environmental data or field evidence used to support a conclusion.", tip: "Separate what the data shows from what it cannot show; include limitations in your final presentation." },
    { id: "environmental-action", kind: "primary", requirementId: "environmental-community-application", requirementLabel: "Applied environmental action", category: "experience", priority: "medium", estimatedHours: 12, coverageTerms: ["environmental action", "conservation project", "sustainability project"], title: () => "Take a measurable role in an environmental or sustainability project", description: () => "Choose a school, community, or official organization activity where you can collect evidence, track an outcome, and explain the environmental trade-off involved.", gap: () => "No applied environmental activity with a measurable contribution is recorded.", tip: "Define one baseline and one outcome measure before starting so the work produces usable evidence." },
    { id: "environmental-interview", kind: "explore", requirementId: "environmental-career-understanding", requirementLabel: "Career understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["environmental scientist interview", "environmental professional interview"], title: () => "Interview an environmental professional or educator about evidence and trade-offs", description: () => "Ask how they evaluate incomplete data, communicate uncertainty, and balance environmental, community, and operational constraints.", gap: () => "No recorded professional perspective on environmental decision-making.", tip: "Ask for one example where new evidence changed the recommended action." },
  ],
  "ai machine learning engineer": [
    { id: "ml-mathematics", kind: "primary", requirementId: "ml-mathematics-statistics", requirementLabel: "Mathematics and statistics", category: "skill", priority: "high", estimatedHours: 18, coverageTerms: ["statistics", "probability", "linear algebra", "calculus"], title: context => `Plan a ${getNationalEducationContext(context.countryCode).label} mathematics and statistics preparation step`, description: context => countryPlanningAction(context, "mathematics, statistics, and computing"), gap: () => "No recorded mathematics or statistics preparation connected to machine-learning work.", tip: "Practice explaining what a distribution, uncertainty interval, or evaluation metric means in plain language." },
    { id: "ml-experiment", kind: "primary", requirementId: "ml-experimentation", requirementLabel: "Model experimentation", category: "project", priority: "high", estimatedHours: 28, coverageTerms: ["machine learning project", "model evaluation", "ml experiment", "classification model"], title: context => levelAction(context, "Run a small supervised-learning experiment with a documented evaluation", "Compare two machine-learning approaches with a reproducible evaluation report"), description: () => "Use an ethical public dataset, split data carefully, document the prediction task, compare performance, and state where the model should not be used.", gap: () => "Your saved work does not yet show a reproducible machine-learning experiment with evaluation evidence.", tip: "Do not treat an accuracy score as the whole story; inspect errors and write one limitation before deciding the model is useful." },
    { id: "ml-data-practice", kind: "primary", requirementId: "ml-data-handling", requirementLabel: "Responsible data handling", category: "skill", priority: "medium", estimatedHours: 12, coverageTerms: ["data cleaning", "dataset documentation", "data pipeline", "data quality"], title: () => "Document a data-cleaning and dataset-quality workflow", description: () => "Select a small dataset, record missing values and assumptions, clean it reproducibly, and explain how data limitations could affect a model.", gap: () => "No evidence shows a careful data-quality workflow before model building.", tip: "Keep raw and cleaned data separate, and write down every transformation so another student could repeat it." },
    { id: "ml-research-explore", kind: "explore", requirementId: "ml-research-understanding", requirementLabel: "Machine-learning career understanding", category: "experience", priority: "low", estimatedHours: 4, coverageTerms: ["machine learning interview", "ml researcher interview"], title: () => "Read and discuss one accessible machine-learning evaluation or ethics case", description: context => `Choose a trusted educational or research source and identify the task, evidence, limitation, and stakeholder impact. ${countryPlanningAction(context, "responsible technology learning")}`, gap: () => "No recorded perspective on how machine-learning systems are evaluated in practice.", tip: "Ask what would make the system unreliable or unfair before focusing on what it can do." },
  ],
  lawyer: [
    { id: "law-reading-writing", kind: "primary", requirementId: "law-analytical-writing", requirementLabel: "Analytical reading and writing", category: "skill", priority: "high", estimatedHours: 14, coverageTerms: ["legal writing", "argument essay", "analytical writing", "debate brief"], title: () => "Complete an evidence-based argument-writing practice", description: context => countryPlanningAction(context, "advanced reading, writing, and argumentation"), gap: () => "No recorded sustained analytical writing tied to evidence and counterarguments.", tip: "State your claim early, cite evidence precisely, and include the strongest reasonable counterargument before responding to it." },
    { id: "law-evidence-analysis", kind: "primary", requirementId: "law-evidence-analysis", requirementLabel: "Evidence analysis", category: "project", priority: "high", estimatedHours: 18, coverageTerms: ["case analysis", "evidence analysis", "moot court", "legal research"], title: () => "Analyze a public case or policy question using claims and evidence", description: () => "Use reputable public material to separate facts, claims, sources, and unknowns; write a brief that explains the reasoning without offering legal advice.", gap: () => "Your saved work does not yet demonstrate structured evidence analysis.", tip: "Label what a source proves, what it suggests, and what it does not establish." },
    { id: "law-speaking", kind: "primary", requirementId: "law-oral-advocacy", requirementLabel: "Reasoned communication", category: "experience", priority: "medium", estimatedHours: 10, coverageTerms: ["debate", "mock trial", "public speaking", "advocacy"], title: () => "Practice a structured oral argument or evidence-based presentation", description: () => "Join or organize a debate, mock-trial, student council, or civic discussion activity that requires you to respond fairly to another position.", gap: () => "No activity currently records reasoned oral communication under questioning.", tip: "Prepare a one-sentence answer, a supporting reason, and one question that would improve your understanding of the other side." },
    { id: "law-pathway-explore", kind: "explore", requirementId: "law-pathway-understanding", requirementLabel: "Legal education pathway", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["lawyer interview", "legal educator interview"], title: () => "Explore one official legal-education pathway source", description: context => `${countryPlanningAction(context, "legal education and civic learning")} Do not assume any admission or licensing rule; review official guidance only.`, gap: () => "No verified understanding of how legal education pathways are structured in your planning context.", tip: "Save the official source and note which parts are general guidance versus institution-specific requirements." },
  ],
  "product manager": [
    { id: "pm-user-research", kind: "primary", requirementId: "pm-user-research", requirementLabel: "User research", category: "experience", priority: "high", estimatedHours: 10, coverageTerms: ["user interview", "usability research", "customer research", "product research"], title: () => "Run a small user-research study around a real problem", description: () => "Define a user group, ask neutral questions, synthesize recurring needs, and keep raw observations distinct from your interpretations.", gap: () => "No recorded user-research evidence shows how you identify a problem before proposing a solution.", tip: "Ask about a recent task and its obstacles rather than asking whether people would use an idea." },
    { id: "pm-prioritization", kind: "primary", requirementId: "pm-prioritization", requirementLabel: "Product prioritization", category: "project", priority: "high", estimatedHours: 20, coverageTerms: ["product roadmap", "feature prioritization", "product brief", "product case study"], title: () => "Create a product brief with an explicit priority trade-off", description: () => "Turn research into a problem statement, define success, choose a limited release, and explain why two appealing features are not first.", gap: () => "Your saved work does not yet show a product decision grounded in user evidence and trade-offs.", tip: "Use a simple impact-versus-effort view, then write down the assumption that could change the decision." },
    { id: "pm-technical-literacy", kind: "primary", requirementId: "pm-technical-literacy", requirementLabel: "Technical collaboration", category: "skill", priority: "medium", estimatedHours: 12, coverageTerms: ["technical specification", "software collaboration", "product technical"], title: () => "Translate a product idea into a clear technical handoff", description: context => `${countryPlanningAction(context, "technology and communication preparation")} Draft a user flow, acceptance criteria, and open questions for a technical collaborator.`, gap: () => "No recorded evidence shows you can communicate a product need clearly to technical collaborators.", tip: "Describe the user outcome and constraint before proposing an implementation." },
    { id: "pm-explore", kind: "explore", requirementId: "pm-career-understanding", requirementLabel: "Product practice understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["product manager interview", "product leadership interview"], title: () => "Interview a product practitioner about one prioritization decision", description: () => "Ask what evidence changed the roadmap, how disagreement was resolved, and what outcome mattered most after launch.", gap: () => "No direct perspective on cross-functional product decision-making is recorded.", tip: "Focus on a decision with constraints, not only on a product success story." },
  ],
  "cybersecurity analyst": [
    { id: "security-systems", kind: "primary", requirementId: "security-systems-foundations", requirementLabel: "Systems and networking foundations", category: "skill", priority: "high", estimatedHours: 16, coverageTerms: ["networking", "operating systems", "linux", "systems administration"], title: () => "Plan a systems and networking foundation step", description: context => countryPlanningAction(context, "computing, systems, and networking"), gap: () => "No recorded systems or networking preparation supports security analysis work yet.", tip: "Build a simple diagram of how a request moves through a device, network, service, and log before studying attacks." },
    { id: "security-lab", kind: "primary", requirementId: "security-safe-lab", requirementLabel: "Safe security investigation", category: "project", priority: "high", estimatedHours: 22, coverageTerms: ["security lab", "ctf writeup", "threat model", "security project"], title: () => "Complete an authorized security lab or threat-model write-up", description: () => "Use a legal sandbox, capture-the-flag platform, or a fictional system; identify assets, threats, controls, and evidence without testing real systems you do not own or have permission to assess.", gap: () => "No recorded evidence shows a safe, authorized security-analysis workflow.", tip: "Write permission and scope at the top of every security exercise before documenting findings." },
    { id: "security-incident", kind: "primary", requirementId: "security-incident-communication", requirementLabel: "Incident communication", category: "experience", priority: "medium", estimatedHours: 10, coverageTerms: ["incident response", "security briefing", "risk communication"], title: () => "Create a concise incident-response communication plan", description: () => "Use a fictional scenario to decide what happened, what is unknown, who needs to know, and what immediate containment steps are appropriate.", gap: () => "No activity currently demonstrates clear communication under a security-risk scenario.", tip: "Separate confirmed facts, working hypotheses, and next checks so readers do not confuse uncertainty with certainty." },
    { id: "security-explore", kind: "explore", requirementId: "security-career-understanding", requirementLabel: "Security career understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["cybersecurity interview", "security analyst interview"], title: () => "Explore an official cyber-safety or security-career resource", description: context => `${countryPlanningAction(context, "cyber-safety and technology learning")} Prioritize sources that explain lawful, defensive practice.`, gap: () => "No recorded perspective on defensive and ethical security work.", tip: "Treat authorization, privacy, and safe disclosure as core technical requirements, not optional extras." },
  ],
  "data scientist": [
    { id: "data-statistics", kind: "primary", requirementId: "data-statistics-foundation", requirementLabel: "Statistics foundation", category: "skill", priority: "high", estimatedHours: 16, coverageTerms: ["statistics", "probability", "data analysis course", "mathematics"], title: () => "Plan a statistics and data-analysis preparation step", description: context => countryPlanningAction(context, "mathematics, statistics, and data analysis"), gap: () => "No recorded statistics preparation supports careful data interpretation yet.", tip: "Practice identifying the population, sample, possible bias, and uncertainty before drawing a conclusion from any chart." },
    { id: "data-investigation", kind: "primary", requirementId: "data-analysis-evidence", requirementLabel: "Data investigation", category: "project", priority: "high", estimatedHours: 24, coverageTerms: ["data analysis project", "data visualization project", "dataset investigation", "data science project"], title: context => levelAction(context, "Analyze a small public dataset and communicate one careful finding", "Build a reproducible data investigation with a documented question, method, and limitation"), description: () => "Select a question, clean and inspect data, make an appropriate visualization, explain uncertainty, and publish a short evidence-first report.", gap: () => "Your saved work does not yet show an end-to-end data investigation.", tip: "Choose the simplest chart that answers the question, then state what the chart cannot prove." },
    { id: "data-communication", kind: "primary", requirementId: "data-communication", requirementLabel: "Data communication", category: "experience", priority: "medium", estimatedHours: 8, coverageTerms: ["data presentation", "data story", "analytics presentation"], title: () => "Present a data finding to a non-technical audience", description: () => "Create a short briefing that explains the question, evidence, uncertainty, and recommended next question without overstating the result.", gap: () => "No activity shows you translating a data finding for a non-technical audience.", tip: "Put the decision question before the chart and define any technical term the audience may not know." },
    { id: "data-explore", kind: "explore", requirementId: "data-career-understanding", requirementLabel: "Data work understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["data scientist interview", "analyst interview"], title: () => "Interview a data practitioner about an uncertain conclusion", description: () => "Ask how they decided whether data was good enough, what assumption mattered most, and how they explained uncertainty to a stakeholder.", gap: () => "No direct perspective on real-world data-quality trade-offs is recorded.", tip: "Ask for an example where an apparently clear pattern turned out to be misleading." },
  ],
  "aerospace engineer astronaut pathway": [
    { id: "aerospace-physics", kind: "primary", requirementId: "aerospace-physics-mathematics", requirementLabel: "Physics and mathematics", category: "skill", priority: "high", estimatedHours: 18, coverageTerms: ["physics", "advanced mathematics", "calculus", "engineering physics"], title: () => "Plan a physics and mathematics preparation step for aerospace systems", description: context => countryPlanningAction(context, "physics, mathematics, and engineering preparation"), gap: () => "No recorded physics and mathematics preparation supports aerospace systems work yet.", tip: "Connect each concept to a system question: forces, energy, motion, measurement error, or a safety margin." },
    { id: "aerospace-systems", kind: "primary", requirementId: "aerospace-systems-design", requirementLabel: "Systems design", category: "project", priority: "high", estimatedHours: 26, coverageTerms: ["aerospace project", "engineering systems project", "flight simulation", "rocket design"], title: () => "Build a documented engineering systems model or test plan", description: () => "Choose a safe model, simulator, or design challenge; define requirements, interfaces, a failure mode, and how you would test the design.", gap: () => "Your saved work does not yet show systems-level engineering reasoning.", tip: "Record one assumption, one failure mode, and one test for every major design choice." },
    { id: "aerospace-teamwork", kind: "primary", requirementId: "aerospace-team-safety", requirementLabel: "Safety-focused teamwork", category: "experience", priority: "medium", estimatedHours: 12, coverageTerms: ["robotics team", "engineering team", "safety review", "mission planning"], title: () => "Contribute to a team engineering review with a safety lens", description: () => "Use a robotics, engineering, or maker team to identify a risk, propose a control, and explain how the team would know whether it worked.", gap: () => "No activity records safety-oriented engineering teamwork.", tip: "Invite a teammate to challenge your plan; systems improve when assumptions can be questioned early." },
    { id: "aerospace-explore", kind: "explore", requirementId: "aerospace-pathway-understanding", requirementLabel: "Aerospace pathway understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["aerospace engineer interview", "space professional interview"], title: () => "Explore an official aerospace or engineering education pathway", description: context => `${countryPlanningAction(context, "aerospace and engineering learning")} Do not assume a national programme or astronaut-selection route applies to you.`, gap: () => "No verified understanding of relevant local aerospace or engineering pathways is recorded.", tip: "Separate the broad engineering pathway from selective roles; identify the next learning step you can control now." },
  ],
  "mechanical engineer": [
    { id: "mechanical-foundations", kind: "primary", requirementId: "mechanical-math-physics", requirementLabel: "Mechanics, mathematics, and physics", category: "skill", priority: "high", estimatedHours: 16, coverageTerms: ["mechanics", "physics", "engineering mathematics", "advanced mathematics"], title: () => "Plan a mechanics and physics preparation step", description: context => countryPlanningAction(context, "mathematics, physics, and engineering fundamentals"), gap: () => "No recorded mechanics or physics preparation supports mechanical-engineering work yet.", tip: "For each problem, write the system boundary and forces before calculating anything." },
    { id: "mechanical-design", kind: "primary", requirementId: "mechanical-cad-prototyping", requirementLabel: "Design and prototyping", category: "project", priority: "high", estimatedHours: 24, coverageTerms: ["cad project", "mechanical prototype", "engineering prototype", "3d model"], title: () => "Design, model, and test a small mechanical component", description: () => "Define the function, constraints, materials, drawing or CAD model, prototype or simulation, and one test result with a documented revision.", gap: () => "Your saved work does not yet show a mechanical design-to-test cycle.", tip: "Keep the first prototype intentionally simple; testing one assumption is more valuable than adding many untested features." },
    { id: "mechanical-manufacturing", kind: "primary", requirementId: "mechanical-manufacturing-thinking", requirementLabel: "Manufacturing awareness", category: "experience", priority: "medium", estimatedHours: 10, coverageTerms: ["manufacturing project", "maker space", "fabrication", "workshop"], title: () => "Compare two ways a designed component could be made", description: () => "Use a school workshop, maker space, or research exercise to compare cost, material, safety, tolerance, and repair considerations for a bounded component.", gap: () => "No recorded work connects a design decision to manufacturing or maintainability.", tip: "Document why the easier-to-build option might still be a poor choice for the intended use." },
    { id: "mechanical-explore", kind: "explore", requirementId: "mechanical-career-understanding", requirementLabel: "Mechanical engineering understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["mechanical engineer interview", "manufacturing engineer interview"], title: () => "Interview an engineering professional about a design trade-off", description: () => "Ask how cost, reliability, material choice, safety, and testing changed one engineering decision.", gap: () => "No direct perspective on professional mechanical design trade-offs is recorded.", tip: "Ask what they would test first if they could redesign the component today." },
  ],
  architect: [
    { id: "architecture-design", kind: "primary", requirementId: "architecture-spatial-design", requirementLabel: "Spatial design and geometry", category: "skill", priority: "high", estimatedHours: 14, coverageTerms: ["geometry", "architecture design", "spatial design", "design studio"], title: () => "Build spatial-design and geometry preparation", description: context => countryPlanningAction(context, "geometry, visual design, and built-environment learning"), gap: () => "No recorded spatial-design or geometry preparation supports architecture exploration yet.", tip: "Sketch the same space from a user, accessibility, climate, and circulation perspective before settling on a layout." },
    { id: "architecture-portfolio", kind: "primary", requirementId: "architecture-portfolio", requirementLabel: "Architecture portfolio evidence", category: "project", priority: "high", estimatedHours: 24, coverageTerms: ["architecture portfolio", "building design project", "site analysis", "design portfolio"], title: () => "Create a documented site and building-design case study", description: () => "Choose a safe familiar site, identify people and constraints, develop sketches or models, explain choices, and include accessibility and environmental considerations.", gap: () => "Your saved work does not yet show a built-environment case study with process evidence.", tip: "Show iterations and rejected ideas; a portfolio should make your reasoning visible, not only show a final image." },
    { id: "architecture-constraints", kind: "primary", requirementId: "architecture-public-impact", requirementLabel: "Public-interest design", category: "experience", priority: "medium", estimatedHours: 10, coverageTerms: ["accessibility audit", "community design", "sustainability design", "built environment"], title: () => "Analyze accessibility and environmental constraints in one public space", description: () => "Observe respectfully from public information or a permitted setting, identify who may face barriers, and propose design questions rather than claiming professional solutions.", gap: () => "No evidence shows you consider people, accessibility, and long-term impact alongside form.", tip: "Frame observations as questions to investigate, particularly when you do not have complete site information." },
    { id: "architecture-explore", kind: "explore", requirementId: "architecture-pathway-understanding", requirementLabel: "Architecture education pathway", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["architect interview", "architecture educator interview"], title: () => "Review an official architecture education or portfolio guidance source", description: context => `${countryPlanningAction(context, "architecture and design education")} Provider requirements differ, so save the source rather than relying on a generic checklist.`, gap: () => "No verified understanding of local architecture education or portfolio expectations is recorded.", tip: "Note whether advice applies to secondary study, portfolio review, or a specific provider before acting on it." },
  ],
  "ux product designer": [
    { id: "ux-research", kind: "primary", requirementId: "ux-user-research", requirementLabel: "UX research", category: "experience", priority: "high", estimatedHours: 10, coverageTerms: ["ux research", "usability interview", "user interview", "design research"], title: () => "Run a small accessibility-aware user research study", description: () => "Recruit respectfully, ask task-based questions, record observations, and identify a need without assuming that your own experience represents every user.", gap: () => "No recorded research evidence shows how you identify user needs before designing.", tip: "Ask participants to show or describe a recent task; avoid leading them toward the answer you expect." },
    { id: "ux-prototype", kind: "primary", requirementId: "ux-interaction-prototyping", requirementLabel: "Interaction design and prototyping", category: "project", priority: "high", estimatedHours: 22, coverageTerms: ["ux portfolio", "interaction prototype", "usability test", "design prototype"], title: () => "Design and test an interactive prototype for one user task", description: () => "Create a clear user flow, prototype the important states, test it with a small number of users, and document what changed after feedback.", gap: () => "Your saved work does not yet show an interaction-design cycle with usability evidence.", tip: "Test a concrete task, not whether people generally like the design; record where they hesitate or misunderstand." },
    { id: "ux-visual-system", kind: "primary", requirementId: "ux-visual-communication", requirementLabel: "Visual communication", category: "skill", priority: "medium", estimatedHours: 10, coverageTerms: ["visual design", "design system", "accessibility design", "ui design"], title: () => "Create a small accessible visual-design system", description: context => `${countryPlanningAction(context, "visual design and communication learning")} Define typography, color contrast, component states, and one accessibility decision.`, gap: () => "No recorded work shows consistent visual communication with accessibility considerations.", tip: "Check contrast and focus states early; accessibility is part of the design system, not a final polish step." },
    { id: "ux-explore", kind: "explore", requirementId: "ux-career-understanding", requirementLabel: "Design practice understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["ux designer interview", "product designer interview"], title: () => "Interview a designer about one usability trade-off", description: () => "Ask how research changed a design, which users were hardest to serve, and how the team balanced usability with other constraints.", gap: () => "No direct perspective on evidence-driven design practice is recorded.", tip: "Ask what the team learned from a user behavior that surprised them." },
  ],
  "financial analyst": [
    { id: "finance-foundations", kind: "primary", requirementId: "finance-math-economics", requirementLabel: "Mathematics and economics foundation", category: "skill", priority: "high", estimatedHours: 16, coverageTerms: ["economics", "finance course", "accounting", "statistics"], title: () => "Plan mathematics, economics, or accounting preparation", description: context => countryPlanningAction(context, "mathematics, economics, accounting, or business analysis"), gap: () => "No recorded academic preparation supports financial-analysis work yet.", tip: "When reading any financial claim, identify the period, assumptions, and data source before comparing numbers." },
    { id: "finance-model", kind: "primary", requirementId: "finance-modeling", requirementLabel: "Financial modeling", category: "project", priority: "high", estimatedHours: 22, coverageTerms: ["financial model", "spreadsheet model", "valuation project", "financial analysis project"], title: context => levelAction(context, "Build a transparent spreadsheet model for a small scenario", "Build and document a sensitivity-tested financial model"), description: () => "Use a clearly fictional or public-data scenario, state assumptions, calculate outcomes, and show how a change in one assumption affects the result.", gap: () => "Your saved work does not yet show a transparent financial model with assumptions and sensitivity analysis.", tip: "Separate inputs, calculations, and outputs so another person can challenge an assumption without breaking the whole model." },
    { id: "finance-communication", kind: "primary", requirementId: "finance-communication", requirementLabel: "Financial communication", category: "experience", priority: "medium", estimatedHours: 8, coverageTerms: ["financial presentation", "investment briefing", "business presentation"], title: () => "Write a concise evidence-first financial briefing", description: () => "Explain a scenario, the key evidence, assumptions, risks, and one cautious recommendation without presenting it as investment advice.", gap: () => "No activity demonstrates communicating financial evidence and uncertainty clearly.", tip: "Use conditional language and distinguish a model output from a real-world prediction or recommendation." },
    { id: "finance-explore", kind: "explore", requirementId: "finance-pathway-understanding", requirementLabel: "Finance pathway understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["financial analyst interview", "finance professional interview"], title: () => "Explore one official finance or economics education pathway source", description: context => `${countryPlanningAction(context, "finance and economics education")} Do not rely on general career claims for regulated or institution-specific pathways.`, gap: () => "No verified understanding of relevant finance education pathways is recorded.", tip: "Record the source, its jurisdiction, and whether it describes general preparation or a specific credential." },
  ],
  "research scientist": [
    { id: "research-foundations", kind: "primary", requirementId: "research-scientific-foundations", requirementLabel: "Scientific and quantitative foundations", category: "skill", priority: "high", estimatedHours: 16, coverageTerms: ["advanced science", "statistics", "research methods", "scientific methods"], title: () => "Plan a scientific and quantitative preparation step", description: context => countryPlanningAction(context, "science, mathematics, statistics, and research methods"), gap: () => "No recorded foundation connects scientific learning to a research-methods workflow.", tip: "For each scientific topic, practice forming a testable question and naming what evidence would change your mind." },
    { id: "research-investigation", kind: "primary", requirementId: "research-methods-evidence", requirementLabel: "Research methods", category: "project", priority: "high", estimatedHours: 26, coverageTerms: ["research project", "scientific investigation", "experimental design", "research paper"], title: context => levelAction(context, "Complete a small reproducible investigation", "Develop a documented research project with method, analysis, and limitations"), description: () => "Define a question, ethical scope, method, evidence plan, analysis, limitation, and next experiment using safe school, community, or public-data work.", gap: () => "Your saved work does not yet show a reproducible research-methods cycle.", tip: "Write the method before seeing the result so you can distinguish a planned test from a post-hoc explanation." },
    { id: "research-writing", kind: "primary", requirementId: "research-scientific-writing", requirementLabel: "Scientific communication", category: "experience", priority: "medium", estimatedHours: 10, coverageTerms: ["research presentation", "scientific writing", "poster presentation", "lab report"], title: () => "Communicate a research question, method, evidence, and limitation", description: () => "Turn one investigation into a short poster, talk, or report that separates results, interpretation, uncertainty, and the next question.", gap: () => "No activity demonstrates communicating research with limitations and next steps.", tip: "Use a clear claim-evidence-reasoning structure and avoid language that makes one small result sound universal." },
    { id: "research-explore", kind: "explore", requirementId: "research-career-understanding", requirementLabel: "Research pathway understanding", category: "experience", priority: "low", estimatedHours: 3, coverageTerms: ["research scientist interview", "research mentor interview"], title: () => "Discuss a research process with a scientist or educator", description: () => "Ask how they refined a question, handled a result that did not support the hypothesis, and decided what to investigate next.", gap: () => "No direct perspective on iterative research practice is recorded.", tip: "Focus on process and uncertainty; a useful research story includes what did not work." },
  ],
};

export function getCareerRequirementActions(career: string): CareerRequirementAction[] {
  const key = normalize(career);
  return profiles[key] ?? (key === "machine learning engineer" ? profiles["ai machine learning engineer"] : []);
}

export function actionIsCovered(action: CareerRequirementAction, evidence: string[]) {
  return evidence.some(value => action.coverageTerms.some(term => normalize(value).includes(normalize(term))));
}

export function metadataForAction(action: CareerRequirementAction, context: CareerRecommendationContext): CareerRecommendationMetadata {
  return {
    kind: action.kind,
    requirementId: action.requirementId,
    requirementLabel: action.requirementLabel,
    studentGap: action.gap(context),
    tip: action.tip,
    countryContext: getNationalEducationContext(context.countryCode).label,
    verificationStatus: "general",
    sourceLabel: "General recommendation — verify local availability",
  };
}
