import { trpc } from "@/lib/trpc";
import { Database, ShieldCheck } from "lucide-react";

export function CrossProductEvidencePolicyPanel() {
  const summary = trpc.pathpilot.evidencePolicy.summary.useQuery();
  if (summary.isLoading) return <section className="surface-panel mt-4 p-4"><p className="text-xs text-muted-foreground">Loading your evidence-policy summary…</p></section>;
  if (summary.error || !summary.data) return <section className="surface-panel mt-4 p-4"><p className="text-sm font-semibold">Evidence policy</p><p className="mt-2 text-xs leading-5 text-muted-foreground">This workspace does not combine private records into a personality, ability, motivation, fit, or outcome assessment. The neutral availability summary could not be loaded right now.</p></section>;
  const { policy, availability } = summary.data;
  return <section className="surface-panel mt-4 overflow-hidden"><div className="flex items-start justify-between gap-4 border-b border-slate-200 px-4 py-3 dark:border-slate-700"><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" /><div><p className="text-sm font-semibold">Evidence policy</p><p className="text-xs text-muted-foreground">A read-only boundary for how private record categories may be considered together.</p></div></div><span className="status-tag">Read only</span></div><div className="grid divide-y divide-slate-200 dark:divide-slate-700 lg:grid-cols-[0.9fr_1.1fr] lg:divide-x lg:divide-y-0"><div className="p-4"><div className="flex items-center gap-2"><Database className="size-4 text-primary" /><p className="text-xs font-semibold">Available categories</p></div><p className="mt-2 text-xs leading-5 text-muted-foreground">Only bounded counts are derived; record content stays in its original private source.</p><dl className="mt-3 grid grid-cols-2 gap-2"><div className="border border-slate-200 p-3 dark:border-slate-700"><dt className="text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Completed simulations</dt><dd className="data-value mt-1 text-lg font-semibold">{availability.completedSimulationCount}</dd></div><div className="border border-slate-200 p-3 dark:border-slate-700"><dt className="text-[10px] font-semibold uppercase tracking-[0.1em] text-muted-foreground">Planning activity</dt><dd className="data-value mt-1 text-lg font-semibold">{availability.planningActivityCount}</dd></div></dl><p className="mt-3 text-xs leading-5 text-muted-foreground">{availability.reflectionContextAvailable ? "Both record categories are available for your own reflection. This does not create an automatic action." : "A cross-product reflection context becomes available only after both record categories exist; nothing is inferred while one is missing."}</p></div><div className="p-4"><p className="text-xs font-semibold">What this summary excludes</p><ul className="mt-2 space-y-2 text-xs leading-5 text-muted-foreground">{policy.prohibitedSources.map(item => <li key={item}>• {item}</li>)}</ul><p className="mt-3 text-xs font-semibold">Guardrails</p><ul className="mt-2 space-y-2 text-xs leading-5 text-muted-foreground">{policy.guardrails.map(item => <li key={item}>• {item}</li>)}</ul></div></div></section>;
}
