import type { ConsequenceDefinition, DecisionDefinition, SimulationGraph, TraitSignal } from "../contracts";

type CareerTheme = { id: string; title: string; startId: string; opening: string; evidence: string; stakeholder: string; pressure: string; outcome: string; nouns: { work: string; people: string; evidence: string; plan: string } };
const themes: Record<"health" | "design" | "business", CareerTheme> = {
  health: { id: "health-care-team-v1", title: "Health & care coordination simulation", startId: "care-team-alert", opening: "During a supervised care-team planning exercise, a patient-support plan no longer fits new information. The team has limited time to coordinate a safe next step.", evidence: "The updated notes reveal an assumption in the support plan that needs careful review.", stakeholder: "A teammate raises a concern about how the plan affects the patient and family experience.", pressure: "The handoff window is close, and the team needs a clear, safe recommendation.", outcome: "The team documents a respectful, evidence-aware path forward.", nouns: { work: "support plan", people: "care team", evidence: "updated notes", plan: "handoff plan" } },
  design: { id: "design-feedback-v1", title: "Design & creative systems simulation", startId: "design-feedback-alert", opening: "A student-facing prototype receives conflicting feedback shortly before a review. The team needs to decide what to learn before making the next design change.", evidence: "The feedback reveals that a key user journey works differently for a smaller group of people.", stakeholder: "A teammate asks the group to make the trade-offs visible before committing to a visual direction.", pressure: "The review is close, and the team needs a clear, testable next step.", outcome: "The team documents a user-centered direction and a follow-up learning plan.", nouns: { work: "prototype", people: "design team", evidence: "user feedback", plan: "review plan" } },
  business: { id: "business-decision-v1", title: "Business & entrepreneurship simulation", startId: "business-signal-alert", opening: "A student venture team receives a market signal that challenges its launch assumptions. The team has limited time to decide what evidence should guide the next move.", evidence: "The signal suggests that one customer group may value the offer differently than the original plan assumed.", stakeholder: "A teammate asks the group to compare the customer impact, cost, and timing before moving forward.", pressure: "A pitch review is close, and the team needs a transparent recommendation.", outcome: "The team documents a responsible decision and a learning question for the next cycle.", nouns: { work: "launch plan", people: "venture team", evidence: "market signal", plan: "pitch plan" } },
};

const signal = (trait: TraitSignal["trait"], context: TraitSignal["context"], weight: 1 | 2 | 3 = 1): TraitSignal => ({ trait, direction: 1, weight, context });
const consequence = (id: string, message: string, kind: ConsequenceDefinition["kind"]): ConsequenceDefinition[] => [{ id, message, kind }];

function decision(id: string, label: string, signals: TraitSignal[], next: string, consequences: ConsequenceDefinition[], statePatch?: DecisionDefinition["statePatch"]): DecisionDefinition { return { id, label, signals, next, consequences, statePatch }; }

function buildCareerGraph(theme: CareerTheme): SimulationGraph {
  const n = theme.nouns;
  const start = theme.startId;
  return { id: theme.id, title: theme.title, startNodeId: start, nodes: {
    [start]: { id: start, title: "A plan needs a second look", situation: theme.opening, contexts: ["uncertainty", "time_pressure", "interpersonal"], difficulty: 2, decisions: [
      decision("gather-evidence", `Review the ${n.evidence} before changing the ${n.work}.`, [signal("analytical_thinking", "uncertainty", 2), signal("attention_to_detail", "technical")], "evidence-review", consequence("evidence-opened", "The team now has clearer evidence to discuss, though the time window is tighter.", "learning"), { timePressure: 1, discoveredInformation: ["career-specific-evidence"] }),
      decision("invite-perspective", `Invite a teammate to identify who could be affected by the ${n.work}.`, [signal("collaboration", "interpersonal", 2), signal("ethical_reasoning", "ethical")], "stakeholder-review", consequence("perspective-added", "A wider perspective is now part of the next decision.", "team"), { teamTrust: 1 }),
      decision("move-with-assumption", `Keep the current ${n.plan} and record the assumption for later review.`, [{ trait: "adaptability", direction: 1, weight: 1, context: "time_pressure" }, { trait: "long_term_thinking", direction: -1, weight: 2, context: "planning" }], "pressure-review", consequence("assumption-carried", "The team preserved momentum, but an important assumption remains unresolved.", "caution"), { riskExposure: 1, unresolvedEvents: ["unreviewed-assumption"] }),
    ] },
    "evidence-review": { id: "evidence-review", title: "The evidence changes the question", situation: theme.evidence, contexts: ["technical", "uncertainty", "planning"], difficulty: 2, decisions: [
      decision("test-small-change", `Test one small change to the ${n.work} and compare the outcome.`, [signal("problem_solving", "technical", 2), signal("systems_thinking", "planning")], "tradeoff-review", consequence("small-test", "A smaller experiment makes the next trade-off easier to explain.", "learning"), { projectHealth: 1 }),
      decision("document-condition", `Document the evidence and define a condition before the ${n.people} proceeds.`, [signal("attention_to_detail", "technical", 2), signal("long_term_thinking", "planning")], "tradeoff-review", consequence("condition-documented", "The team now has a shared condition for moving forward.", "progress"), { projectHealth: 1 }),
      decision("narrow-scope", `Narrow the ${n.work} so the team can protect the most important outcome.`, [signal("adaptability", "resource_constraint", 2), signal("ownership", "planning")], "tradeoff-review", consequence("scope-narrowed", "The team protected a smaller, more testable path.", "progress"), { projectHealth: 1 }),
    ] },
    "stakeholder-review": { id: "stakeholder-review", title: "Impact is part of the decision", situation: theme.stakeholder, contexts: ["interpersonal", "ethical", "planning"], difficulty: 2, decisions: [
      decision("map-impact", "Map the benefits, risks, and open questions before recommending a path.", [signal("systems_thinking", "planning", 2), signal("ethical_reasoning", "ethical")], "tradeoff-review", consequence("impact-mapped", "The recommendation can now name both impact and uncertainty.", "learning"), { teamTrust: 1 }),
      decision("seek-feedback", "Ask for a short review from someone who has not worked on the plan.", [signal("communication", "interpersonal", 2), signal("adaptability", "uncertainty")], "tradeoff-review", consequence("outside-feedback", "A fresh perspective is available before the final recommendation.", "team"), { timePressure: 1, teamTrust: 1 }),
      decision("explain-priority", "Explain the current priority and invite a focused challenge to it.", [signal("ownership", "planning"), signal("communication", "interpersonal", 2)], "tradeoff-review", consequence("priority-challenged", "The group has a clearer priority and a record of what still needs review.", "team"), { teamTrust: 1 }),
    ] },
    "pressure-review": { id: "pressure-review", title: "Time pressure reveals a trade-off", situation: theme.pressure, contexts: ["time_pressure", "uncertainty", "resource_constraint"], difficulty: 3, decisions: [
      decision("surface-risk", "Surface the unresolved assumption and ask accountable people to choose the next step.", [signal("communication", "time_pressure", 2), signal("ownership", "planning")], "tradeoff-review", consequence("risk-surfaced", "The risk is now visible to the people deciding how to proceed.", "progress"), { teamTrust: 1 }),
      decision("protect-core", "Protect the validated core path and defer the uncertain work with a clear rationale.", [signal("attention_to_detail", "technical", 2), signal("adaptability", "time_pressure")], "tradeoff-review", consequence("core-protected", "The team reduced exposure while keeping a usable path forward.", "progress"), { projectHealth: 1, riskExposure: -1 }),
      decision("rush-ahead", "Move ahead without another review so the deadline is preserved.", [{ trait: "ownership", direction: 1, weight: 1, context: "time_pressure" }, { trait: "ethical_reasoning", direction: -1, weight: 2, context: "ethical" }], "tradeoff-review", consequence("review-skipped", "The deadline is protected, but the team carries more uncertainty into the next stage.", "caution"), { riskExposure: 2, projectHealth: -1 }),
    ] },
    "tradeoff-review": { id: "tradeoff-review", title: "Choose what the plan protects", situation: "The team has enough information to make a bounded choice. The question is how to balance the immediate outcome with what the group learns next.", contexts: ["planning", "execution", "ethical"], difficulty: 3, decisions: [
      decision("recommend-evidence", "Recommend the option that best matches the available evidence and name its limitation.", [signal("analytical_thinking", "planning", 2), signal("ethical_reasoning", "ethical")], "implementation-plan", consequence("evidence-recommendation", "The recommendation is grounded in what the team knows and what it does not.", "learning"), { projectHealth: 1 }),
      decision("stage-decision", "Recommend a staged decision with a review point before committing further.", [signal("long_term_thinking", "planning", 2), signal("systems_thinking", "execution")], "implementation-plan", consequence("staged-decision", "The plan now includes a deliberate review point rather than a one-way commitment.", "progress"), { riskExposure: -1 }),
      decision("coordinate-alignment", "Coordinate a short alignment conversation before the team starts work.", [signal("collaboration", "interpersonal", 2), signal("communication", "planning")], "implementation-plan", consequence("team-aligned", "Dependencies and concerns are clearer before the work begins.", "team"), { teamTrust: 1 }),
    ] },
    "implementation-plan": { id: "implementation-plan", title: "Make the next step observable", situation: `The ${n.people} now needs an implementation plan that makes ownership, validation, and communication visible.`, contexts: ["execution", "planning", "interpersonal"], difficulty: 2, decisions: [
      decision("assign-checkpoint", "Assign an owner and a measurable checkpoint for reviewing the outcome.", [signal("ownership", "execution", 2), signal("attention_to_detail", "planning")], "outcome-review", consequence("checkpoint-set", "The team has a named review point for learning from the outcome.", "progress"), { projectHealth: 1 }),
      decision("coordinate-dependencies", "Make dependencies explicit and coordinate the handoff with the team.", [signal("collaboration", "interpersonal", 2), signal("systems_thinking", "planning")], "outcome-review", consequence("dependencies-visible", "The team has a clearer shared picture of the work ahead.", "team"), { teamTrust: 1 }),
      decision("start-small", "Start the smallest safe piece of work and report back with evidence.", [signal("adaptability", "resource_constraint", 2), signal("problem_solving", "execution")], "outcome-review", consequence("small-start", "The next step is small enough to learn from without overcommitting.", "learning"), { projectHealth: 1 }),
    ] },
    "outcome-review": { id: "outcome-review", title: "Close the learning loop", situation: theme.outcome, contexts: ["failure", "planning", "interpersonal"], difficulty: 2, decisions: [
      decision("capture-learning", "Capture the evidence, decision rationale, and one question for next time.", [signal("long_term_thinking", "planning", 2), signal("analytical_thinking", "failure")], "learning-plan", consequence("learning-captured", "The team has a reusable record for a similar future decision.", "learning"), { projectHealth: 1 }),
      decision("request-feedback", "Request feedback on how the team communicated the trade-off.", [signal("communication", "interpersonal", 2), signal("adaptability", "planning")], "learning-plan", consequence("feedback-requested", "The team created a chance to improve how it handles difficult conversations.", "team"), { teamTrust: 1 }),
      decision("name-follow-up", "Name one follow-up review before moving to the next priority.", [signal("ownership", "planning"), signal("long_term_thinking", "planning")], "learning-plan", consequence("follow-up-named", "The learning work has a concrete next review rather than an open-ended intention.", "progress"), { unresolvedEvents: [] }),
    ] },
    "learning-plan": { id: "learning-plan", title: "Choose the next learning move", situation: "One final choice will determine what evidence and practice the team carries into its next project.", contexts: ["planning", "execution"], difficulty: 2, decisions: [
      decision("practice-skill", "Practice one decision skill through a small, evidence-focused project.", [signal("ownership", "execution"), signal("long_term_thinking", "planning")], "debrief", consequence("practice-selected", "A specific learning move is now connected to the experience.", "progress")),
      decision("review-evidence", "Review the outcome with the team before deciding what to change next.", [signal("analytical_thinking", "planning"), signal("collaboration", "interpersonal")], "debrief", consequence("review-selected", "The team will revisit the outcome with shared evidence.", "learning")),
      decision("seek-mentor", "Ask a mentor or teacher for feedback on the trade-off and communication.", [signal("communication", "interpersonal"), signal("adaptability", "planning")], "debrief", consequence("mentor-feedback", "An external perspective is part of the next learning step.", "team")),
    ] },
    debrief: { id: "debrief", title: "Simulation complete", situation: "Your decisions created a distinct path through this work situation. PathPilot can now summarize learning signals from the choices you made.", contexts: ["planning"], difficulty: 1, decisions: [], terminal: true },
  } };
}

export const healthV1Graph = buildCareerGraph(themes.health);
export const designV1Graph = buildCareerGraph(themes.design);
export const businessV1Graph = buildCareerGraph(themes.business);
