import { buildDedicatedCareerGraph, type DedicatedCareerGraphSpec } from "./dedicated-career-graph-builder";

const doctorSpec: DedicatedCareerGraphSpec = {
  id: "doctor-physician-v1",
  title: "Doctor / physician clinical simulation",
  prefix: "doctor",
  traits: ["communication", "ethical_reasoning", "collaboration", "attention_to_detail", "problem_solving", "adaptability"],
  stages: [
    { id: "doctor-triage", title: "Triage with incomplete information", situation: "A patient arrives with worsening chest discomfort, but the first details are incomplete and several patients are waiting. The clinical team needs a safe next move.", contexts: ["uncertainty", "time_pressure", "ethical"], difficulty: 3, choices: ["Ask focused questions and repeat vital signs before assigning priority.", "Coordinate a rapid assessment with the nurse and explain the uncertainty.", "Send the patient to the end of the queue because the first signs look stable."], next: ["doctor-testing", "doctor-team-brief", "doctor-deterioration"], messages: ["The team now has a clearer clinical picture before the next decision.", "The care team shares the uncertainty and can coordinate the next assessment.", "The unresolved symptoms remain visible as the waiting room pressure grows."] },
    { id: "doctor-testing", title: "Conflicting clinical signals", situation: "The follow-up information points in two directions: one result is reassuring, while another could indicate a time-sensitive concern.", contexts: ["technical", "uncertainty", "time_pressure"], difficulty: 3, choices: ["Compare the findings and request the most decision-changing next test.", "Ask a senior clinician to review the conflicting information with you.", "Choose the reassuring result and postpone the uncertain finding."], next: ["doctor-care-plan", "doctor-care-plan", "doctor-deterioration"], messages: ["The next test is connected to the clinical question rather than routine delay.", "A second perspective helps the team name what remains uncertain.", "The unreviewed concern may change the patient's condition later."] },
    { id: "doctor-team-brief", title: "Coordinate the care team", situation: "The nurse reports a subtle change while a family member asks what will happen next. The team needs one shared plan.", contexts: ["interpersonal", "time_pressure", "planning"], difficulty: 2, choices: ["Summarize the current concern, assign the next observation, and update the family honestly.", "Ask the nurse what they are seeing and agree on an escalation threshold together.", "Keep the plan to yourself until every answer is certain."], next: ["doctor-care-plan", "doctor-testing", "doctor-deterioration"], messages: ["The patient, family, and team have a clearer immediate plan.", "The escalation threshold is now visible to the people closest to the patient.", "The missing coordination makes a change harder for the team to notice."] },
    { id: "doctor-deterioration", title: "The condition changes", situation: "The patient becomes more short of breath. The earlier uncertainty now requires a calm, immediate response from the care team.", contexts: ["failure", "time_pressure", "interpersonal"], difficulty: 3, choices: ["Escalate care, stabilize the patient, and communicate the change to the team.", "Recheck the key signs while asking a colleague to prepare the escalation pathway.", "Wait for the next routine observation before changing the plan."], next: ["doctor-care-plan", "doctor-care-plan", "doctor-ethics"], messages: ["The clinical response is now matched to the change in condition.", "Parallel tasks protect both reassessment and readiness to escalate.", "The delay creates an ethical and safety concern for the next conversation."] },
    { id: "doctor-care-plan", title: "Choose a care path", situation: "The team has enough information to discuss a care path, its tradeoffs, and what needs close monitoring.", contexts: ["ethical", "planning", "communication"], difficulty: 3, choices: ["Explain the options, benefits, and uncertainties in language the patient can use.", "Recommend a staged plan with a clear review point if the condition changes.", "Promise the fastest option will definitely solve the problem."], next: ["doctor-resource", "doctor-resource", "doctor-ethics"], messages: ["The patient can participate in a decision with clear, respectful information.", "The care plan includes a specific condition for reassessment.", "The certainty claim creates a trust concern for the next interaction."] },
    { id: "doctor-ethics", title: "A trust and consent concern", situation: "A family member asks for information the patient has not agreed to share. The team must protect care, trust, and communication at the same time.", contexts: ["ethical", "interpersonal", "uncertainty"], difficulty: 3, choices: ["Clarify the patient's wishes and explain the privacy boundary respectfully.", "Ask a supervisor for support in a difficult consent conversation.", "Share the details so the family feels included."], next: ["doctor-resource", "doctor-care-plan", "doctor-reflection"], messages: ["The team protects the patient's voice while keeping communication respectful.", "A supported conversation helps the team handle the boundary carefully.", "The privacy concern now needs explicit reflection and repair."] },
    { id: "doctor-resource", title: "Limited clinical capacity", situation: "A bed and specialist review are both limited. The team must decide how to prioritize without treating one patient as invisible.", contexts: ["resource_constraint", "ethical", "planning"], difficulty: 3, choices: ["Use explicit clinical criteria and communicate the review plan to the team.", "Coordinate a safe interim monitoring plan while arranging the next available review.", "Allocate the resource based on who argues most strongly."], next: ["doctor-handoff", "doctor-handoff", "doctor-reflection"], messages: ["The priority decision is connected to clear clinical reasons and review.", "The interim plan protects observation while capacity is limited.", "The arbitrary allocation creates a concern for the team's reflection."] },
    { id: "doctor-handoff", title: "Make the handoff reliable", situation: "Your shift is ending, but the patient's next team will need the uncertainty, escalation triggers, and care plan to be clear.", contexts: ["planning", "interpersonal", "attention_to_detail"], difficulty: 2, choices: ["Document the decision trail, current concern, and exact escalation triggers.", "Give a structured verbal handoff and invite questions from the next clinician.", "Leave a short note that says to keep watching the patient."], next: ["doctor-follow-up", "doctor-follow-up", "doctor-reflection"], messages: ["The next team can see why the plan exists and when to reassess.", "The handoff creates shared understanding before responsibility changes.", "The vague handoff leaves an important risk unresolved."] },
    { id: "doctor-follow-up", title: "Plan the follow-up", situation: "The immediate issue is more stable. The question now is how to support the patient's recovery and reduce the chance of a missed change.", contexts: ["planning", "communication", "long_term_thinking"], difficulty: 2, choices: ["Co-create a follow-up plan with warning signs and a way to ask questions.", "Check that the patient understands the plan in their own words.", "End the visit once the immediate numbers improve."], next: ["doctor-reflection", "doctor-reflection", "doctor-reflection"], messages: ["The follow-up plan connects recovery to clear next actions.", "The team has evidence that the plan is understandable to the patient.", "The next stage needs reflection on the missing recovery support."] },
    { id: "doctor-reflection", title: "Reflect on clinical reasoning", situation: "Before the case closes, choose how the team will learn from the uncertainty, communication, and decisions in this scenario.", contexts: ["planning", "interpersonal", "failure"], difficulty: 2, choices: ["Practice one communication skill in a future patient conversation.", "Review the evidence and escalation decisions with the team.", "Ask a mentor for feedback on handling uncertainty."], next: ["doctor-debrief-practice", "doctor-debrief-evidence", "doctor-debrief-feedback"], messages: ["A concrete communication practice is connected to this case.", "The team will revisit its reasoning with shared evidence.", "An additional perspective is part of the next learning step."] },
  ],
};

const lawyerSpec: DedicatedCareerGraphSpec = {
  id: "lawyer-v1",
  title: "Lawyer legal strategy simulation",
  prefix: "lawyer",
  traits: ["analytical_thinking", "communication", "ethical_reasoning", "attention_to_detail", "long_term_thinking", "systems_thinking"],
  stages: [
    { id: "lawyer-intake", title: "A client presents a fast-moving dispute", situation: "A client brings a contract dispute with a filing deadline approaching. Their account is confident, but the documents are incomplete.", contexts: ["uncertainty", "time_pressure", "interpersonal"], difficulty: 2, choices: ["Map the timeline and request the missing agreement, messages, and notices.", "Clarify the client's goal and explain what cannot yet be concluded.", "Promise a strong outcome before reviewing the documents."], next: ["lawyer-evidence", "lawyer-negotiation", "lawyer-ethics"], messages: ["The legal question is now connected to a document and timeline review.", "The client has a clearer picture of the immediate legal uncertainty.", "The early promise creates a professional responsibility concern."] },
    { id: "lawyer-evidence", title: "Evidence does not line up", situation: "The documents support part of the client's account, but a message thread suggests a different interpretation of the disputed obligation.", contexts: ["technical", "uncertainty", "ethical"], difficulty: 3, choices: ["Compare each source against the contract language and identify what is still unproven.", "Ask a colleague to challenge your reading before choosing a strategy.", "Set aside the message thread because it complicates the case."], next: ["lawyer-strategy", "lawyer-strategy", "lawyer-testimony"], messages: ["The strategy can distinguish evidence from an assumption.", "A second legal reading helps surface weaknesses before the next step.", "The overlooked message becomes a risk in the later record."] },
    { id: "lawyer-negotiation", title: "The client wants immediate action", situation: "The client asks you to send a forceful demand today. The other party has offered a conversation but no admission.", contexts: ["interpersonal", "planning", "time_pressure"], difficulty: 2, choices: ["Prepare a fact-grounded demand that leaves room for a documented negotiation.", "Explain the tradeoffs and ask what outcome matters most to the client.", "Send an accusation that goes beyond the evidence to increase pressure."], next: ["lawyer-strategy", "lawyer-evidence", "lawyer-ethics"], messages: ["The demand protects the client's position without overstating the record.", "The legal strategy now reflects the client's priorities and risk tolerance.", "The unsupported accusation creates an ethical and credibility concern."] },
    { id: "lawyer-ethics", title: "Professional responsibility is tested", situation: "A client suggests withholding a document that could make their position harder to defend. The deadline is still close.", contexts: ["ethical", "time_pressure", "interpersonal"], difficulty: 3, choices: ["Explain the disclosure duty and preserve the document in the case record.", "Seek ethics guidance before taking any step that could affect the tribunal.", "Agree to leave the document out so the case appears simpler."], next: ["lawyer-strategy", "lawyer-strategy", "lawyer-testimony"], messages: ["The record remains aligned with professional responsibility.", "A careful review protects the client and the integrity of the process.", "The decision creates a serious credibility issue for the next stage."] },
    { id: "lawyer-testimony", title: "A witness account changes", situation: "A witness now remembers events differently than the initial statement. The difference may be honest, but it matters to the case.", contexts: ["uncertainty", "communication", "attention_to_detail"], difficulty: 3, choices: ["Document the change and test which facts the witness can support reliably.", "Prepare the client for how the changed account affects the strategy.", "Coach the witness to return to the original version."], next: ["lawyer-strategy", "lawyer-strategy", "lawyer-remedy"], messages: ["The case can separate reliable facts from uncertain memory.", "The client now understands the legal significance of the changed account.", "The coaching concern requires a corrective professional response."] },
    { id: "lawyer-strategy", title: "Choose a legal strategy", situation: "The record is clearer but still incomplete. You must recommend a path that balances cost, proof, timing, and the client's stated objective.", contexts: ["planning", "analytical_thinking", "resource_constraint"], difficulty: 3, choices: ["Recommend a limited claim supported by the strongest evidence.", "Propose a staged negotiation with clear settlement conditions.", "Pursue every possible argument even where the support is weak."], next: ["lawyer-remedy", "lawyer-remedy", "lawyer-hearing"], messages: ["The proposed claim is aligned with what the evidence can actually support.", "The negotiation plan gives the client clear decision points.", "The overextended strategy adds cost and credibility risk."] },
    { id: "lawyer-hearing", title: "Prepare for a short hearing", situation: "The matter will be heard quickly. The decision maker will need a concise explanation of the facts, law, and uncertainty.", contexts: ["communication", "time_pressure", "planning"], difficulty: 2, choices: ["Organize the strongest evidence and name the limitation of your argument.", "Practice concise answers to the most difficult questions with a colleague.", "Rely on confident presentation instead of revisiting the weak evidence."], next: ["lawyer-remedy", "lawyer-remedy", "lawyer-reflection"], messages: ["The presentation is grounded in the record rather than certainty claims.", "The rehearsal makes the reasoning clearer under pressure.", "The unreviewed weakness becomes visible for reflection."] },
    { id: "lawyer-remedy", title: "Advise on resolution", situation: "A resolution option is available, but it requires the client to weigh cost, risk, and the value of a final answer.", contexts: ["ethical", "interpersonal", "planning"], difficulty: 2, choices: ["Explain the likely benefits, limits, and practical consequences of each option.", "Ask the client to restate their priorities before recommending a resolution.", "Choose the quickest resolution without discussing the tradeoffs."], next: ["lawyer-closeout", "lawyer-closeout", "lawyer-reflection"], messages: ["The client can decide with a clear view of consequence and uncertainty.", "The recommendation is connected to the client's own objective.", "The missing discussion creates a concern for the final review."] },
    { id: "lawyer-closeout", title: "Close the case responsibly", situation: "The immediate legal step is complete. The client needs records, deadlines, and a clear explanation of what follows.", contexts: ["attention_to_detail", "communication", "planning"], difficulty: 2, choices: ["Send a written summary of the outcome, deadlines, and unanswered questions.", "Confirm the client understands the next obligation and contact point.", "Close the file without recording the remaining timing issue."], next: ["lawyer-reflection", "lawyer-reflection", "lawyer-reflection"], messages: ["The client has a usable record for the next legal step.", "The next obligation is understood rather than assumed.", "The missing record becomes a learning point for the reflection."] },
    { id: "lawyer-reflection", title: "Reflect on legal judgment", situation: "Choose how you will carry evidence evaluation, client communication, and professional responsibility into the next matter.", contexts: ["planning", "ethical", "interpersonal"], difficulty: 2, choices: ["Practice building a concise evidence timeline for a future case.", "Review the strategy and record with a peer before the next matter.", "Ask a mentor for feedback on a difficult professional responsibility decision."], next: ["lawyer-debrief-practice", "lawyer-debrief-evidence", "lawyer-debrief-feedback"], messages: ["A practical evidence-review skill is connected to the experience.", "A shared review will test the reasoning and record.", "A mentor perspective is part of the next learning move."] },
  ],
};

const entrepreneurSpec: DedicatedCareerGraphSpec = {
  id: "entrepreneur-startup-founder-v1",
  title: "Entrepreneur / startup founder simulation",
  prefix: "founder",
  traits: ["ownership", "adaptability", "communication", "long_term_thinking", "collaboration", "problem_solving"],
  stages: [
    { id: "founder-signal", title: "A customer signal challenges the plan", situation: "A launch-week customer reports that the product solves the wrong part of their workflow. Your small team has limited runway and competing priorities.", contexts: ["uncertainty", "interpersonal", "resource_constraint"], difficulty: 2, choices: ["Interview the customer and compare their workflow with the original assumption.", "Ask the team to identify which customer signal would most change the roadmap.", "Keep the launch plan because changing direction may worry investors."], next: ["founder-research", "founder-team", "founder-runway"], messages: ["The team now has a direct path to test the product assumption.", "The next customer signal is connected to a specific roadmap decision.", "The untested assumption becomes more costly as runway pressure grows."] },
    { id: "founder-research", title: "The problem is narrower than expected", situation: "The interviews show strong interest from one customer group but weak interest from another. Building for both would stretch the team.", contexts: ["analytical_thinking", "planning", "resource_constraint"], difficulty: 2, choices: ["Define a focused customer segment and test the smallest useful version.", "Compare the expected value of each segment with the team before choosing.", "Add more features for every segment before validating either."], next: ["founder-pricing", "founder-pricing", "founder-runway"], messages: ["The product experiment now has a clear audience and learning goal.", "The team can compare options before committing scarce build time.", "The broader build increases cost before evidence improves."] },
    { id: "founder-team", title: "The team sees different opportunities", situation: "One teammate wants a fast feature release, while another wants to pause for more research. Both are concerned about runway.", contexts: ["interpersonal", "time_pressure", "planning"], difficulty: 2, choices: ["Facilitate a short decision using customer evidence and runway assumptions.", "Split the work into one research task and one reversible product experiment.", "Choose the feature release without hearing the research concern."], next: ["founder-pricing", "founder-research", "founder-team-conflict"], messages: ["The team has a shared basis for choosing a next move.", "The team can learn without treating the decision as irreversible.", "The unresolved disagreement now affects execution and trust."] },
    { id: "founder-runway", title: "Runway is shorter than planned", situation: "The finance update shows fewer months of runway than expected. A supplier payment and a potential pilot both compete for the same funds.", contexts: ["resource_constraint", "time_pressure", "ethical"], difficulty: 3, choices: ["Reforecast cash, name the tradeoffs, and protect the most decision-changing experiment.", "Discuss the runway change transparently with the team before changing commitments.", "Delay the supplier payment without communicating the risk."], next: ["founder-pricing", "founder-team-conflict", "founder-ethics"], messages: ["The cash decision is connected to learning value and explicit tradeoffs.", "The team can adjust with a shared view of the constraint.", "The uncommunicated decision creates a trust and responsibility concern."] },
    { id: "founder-pricing", title: "A pilot customer asks for a discount", situation: "A promising pilot customer wants a lower price and additional support. The deal could generate learning but may create a difficult precedent.", contexts: ["interpersonal", "planning", "ethical"], difficulty: 2, choices: ["Offer a time-bounded pilot with learning goals and clear support limits.", "Compare the customer value, support cost, and precedent with the team.", "Accept every request to secure the logo quickly."], next: ["founder-hiring", "founder-hiring", "founder-operations"], messages: ["The pilot is structured to create evidence without open-ended commitments.", "The tradeoff is now visible before pricing becomes a precedent.", "The commitment may overload the team in the next stage."] },
    { id: "founder-team-conflict", title: "Execution tension appears", situation: "The team feels the decisions are changing too quickly. A key teammate asks what the company will protect when evidence and speed disagree.", contexts: ["interpersonal", "uncertainty", "leadership"], difficulty: 3, choices: ["Name the current priority, the evidence behind it, and when it will be reviewed.", "Invite the teammate to propose a reversible alternative with a clear measure.", "Tell the team to move faster without revisiting the decision."], next: ["founder-hiring", "founder-operations", "founder-ethics"], messages: ["The team has a transparent decision rule and review point.", "The team can test an alternative without treating disagreement as disloyalty.", "The missing explanation makes trust and execution harder."] },
    { id: "founder-ethics", title: "A growth shortcut has a cost", situation: "Someone suggests collecting more customer data than the product needs so sales materials can appear more persuasive.", contexts: ["ethical", "time_pressure", "long_term_thinking"], difficulty: 3, choices: ["Limit collection to the stated purpose and explain the trust tradeoff.", "Ask for a privacy review before changing the data practice.", "Collect everything now and decide how to use it after growth improves."], next: ["founder-operations", "founder-operations", "founder-reflection"], messages: ["The growth decision protects customer trust and stated purpose.", "A review creates a responsible boundary before the practice changes.", "The data shortcut becomes a significant issue for reflection."] },
    { id: "founder-hiring", title: "A hiring decision shapes the team", situation: "A candidate could fill an urgent gap but has little experience with the customers the startup now serves.", contexts: ["planning", "interpersonal", "resource_constraint"], difficulty: 2, choices: ["Define the role's must-have customer and execution capabilities before deciding.", "Use a structured work sample and include the team in the evaluation.", "Hire immediately because waiting might lose the candidate."], next: ["founder-operations", "founder-operations", "founder-reflection"], messages: ["The hiring decision is tied to the work the company now needs to do.", "The team uses evidence rather than urgency alone in the decision.", "The rushed choice leaves a learning point for the next review."] },
    { id: "founder-operations", title: "Turn learning into an operating plan", situation: "The next month needs a small set of commitments across customer learning, product work, and cash management.", contexts: ["planning", "execution", "communication"], difficulty: 2, choices: ["Set a weekly customer-learning measure and one product decision it will inform.", "Assign owners and review points for the most important commitments.", "Keep the plan informal so the team can stay flexible."], next: ["founder-reflection", "founder-reflection", "founder-reflection"], messages: ["The team can see how evidence will shape the next product decision.", "Ownership and review points make commitments visible.", "The informal plan leaves a useful topic for reflection."] },
    { id: "founder-reflection", title: "Reflect on founder judgment", situation: "Choose how you will build on the customer, team, and resource decisions from this startup scenario.", contexts: ["planning", "interpersonal", "failure"], difficulty: 2, choices: ["Practice running a short customer-discovery interview with a learning goal.", "Review the decision trail with the team before the next commitment.", "Ask a founder or mentor for feedback on an uncertainty-heavy tradeoff."], next: ["founder-debrief-practice", "founder-debrief-evidence", "founder-debrief-feedback"], messages: ["A specific customer-learning practice is connected to this experience.", "The team will use shared evidence to review the choices.", "A mentor perspective becomes part of the next learning move."] },
  ],
};

const aerospaceSpec: DedicatedCareerGraphSpec = {
  id: "aerospace-engineer-astronaut-v1",
  title: "Aerospace engineer / astronaut pathway simulation",
  prefix: "aerospace",
  traits: ["systems_thinking", "attention_to_detail", "problem_solving", "collaboration", "ethical_reasoning", "adaptability"],
  stages: [
    { id: "aerospace-telemetry", title: "A telemetry anomaly appears", situation: "During mission preparation, a sensor reading drifts outside its expected range. The launch window is limited, and the systems team needs a grounded response.", contexts: ["technical", "time_pressure", "uncertainty"], difficulty: 3, choices: ["Compare the sensor with redundant data before classifying the anomaly.", "Call a short systems review with propulsion, guidance, and operations.", "Treat the reading as noise because the launch window is close."], next: ["aerospace-diagnostics", "aerospace-mission-brief", "aerospace-risk"], messages: ["The team can distinguish a sensor fault from a broader systems issue.", "Cross-system perspectives are now part of the anomaly assessment.", "The unverified reading becomes a mission-risk concern for the next stage."] },
    { id: "aerospace-diagnostics", title: "The fault crosses a subsystem boundary", situation: "The diagnostics suggest a power fluctuation may be affecting both the sensor and a backup control path.", contexts: ["technical", "systems_thinking", "uncertainty"], difficulty: 3, choices: ["Run a contained test that isolates the power path before changing the mission plan.", "Model the failure chain and name which assumption would change the go/no-go decision.", "Replace the sensor and assume the control path is unrelated."], next: ["aerospace-mission-plan", "aerospace-mission-plan", "aerospace-risk"], messages: ["The next test is connected to the system boundary that matters.", "The team now knows which evidence would change the mission decision.", "The narrow repair leaves a systems risk unresolved."] },
    { id: "aerospace-mission-brief", title: "Crew and mission teams need one picture", situation: "Operations asks whether the anomaly affects crew safety, timeline, or communication. Different teams have partial information.", contexts: ["interpersonal", "planning", "time_pressure"], difficulty: 2, choices: ["Share the known facts, uncertainty, and current safety boundary in one briefing.", "Ask each lead to name the condition that would require a hold.", "Tell the crew there is no issue until the analysis is complete."], next: ["aerospace-mission-plan", "aerospace-diagnostics", "aerospace-risk"], messages: ["The mission team has a shared fact base and a clear uncertainty boundary.", "Hold conditions are now visible across the mission teams.", "The missing communication may weaken readiness for a change."] },
    { id: "aerospace-risk", title: "The launch tradeoff becomes explicit", situation: "The team can launch on time with a remaining uncertainty, or hold for more evidence and lose a narrow mission opportunity.", contexts: ["ethical", "resource_constraint", "time_pressure"], difficulty: 3, choices: ["Recommend a hold until the safety-critical uncertainty is resolved.", "Propose a limited mission configuration with a documented constraint and review.", "Proceed without elevating the concern so the window is not lost."], next: ["aerospace-mission-plan", "aerospace-mission-plan", "aerospace-emergency"], messages: ["The decision protects the evidence threshold for a safety-critical system.", "The constrained plan names what the mission can and cannot safely do.", "The unreported risk creates an emergency pathway for the team."] },
    { id: "aerospace-mission-plan", title: "Plan for a constrained mission", situation: "The evidence now supports a bounded mission plan. The team must define resources, monitoring, and the exact condition for aborting.", contexts: ["planning", "technical", "ethical"], difficulty: 3, choices: ["Set telemetry thresholds, contingency roles, and an abort condition before launch.", "Run a mission rehearsal focused on the most plausible fault response.", "Leave the abort condition flexible so the team can decide later."], next: ["aerospace-resource", "aerospace-resource", "aerospace-emergency"], messages: ["The mission plan links monitoring to explicit safety decisions.", "The rehearsal makes the team’s emergency coordination observable.", "The vague abort condition creates a serious operational concern."] },
    { id: "aerospace-emergency", title: "A system response is needed", situation: "A new alert appears during the critical sequence. The team has seconds to protect the vehicle and crew while preserving useful evidence.", contexts: ["failure", "time_pressure", "collaboration"], difficulty: 3, choices: ["Execute the documented abort or safe-mode protocol and state the reason clearly.", "Assign parallel roles for vehicle safety, telemetry capture, and communication.", "Continue nominal operations while trying to diagnose the alert live."], next: ["aerospace-resource", "aerospace-resource", "aerospace-reflection"], messages: ["The response is connected to the mission's safety protocol and evidence record.", "The team protects safety and coordination through explicit parallel roles.", "The live diagnosis leaves a major risk for the team to reflect on."] },
    { id: "aerospace-resource", title: "Fuel and power margins narrow", situation: "A revised plan has less fuel and power margin than expected. The mission team must choose what work remains essential.", contexts: ["resource_constraint", "planning", "systems_thinking"], difficulty: 2, choices: ["Protect the mission objective with the strongest safety and evidence value.", "Stage the work so each step has a clear resource review point.", "Keep every planned activity and hope the margin holds."], next: ["aerospace-crew", "aerospace-crew", "aerospace-reflection"], messages: ["The resource decision is tied to mission purpose and safety value.", "The staged plan makes resource limits visible before each commitment.", "The unbounded plan creates a concern for mission review."] },
    { id: "aerospace-crew", title: "Coordinate a critical handoff", situation: "A new operations team is taking over. They need the current constraint, monitoring plan, and decision authority to be unambiguous.", contexts: ["communication", "attention_to_detail", "interpersonal"], difficulty: 2, choices: ["Deliver a structured handoff with constraints, thresholds, and authority clearly recorded.", "Ask the incoming team to repeat the abort condition and next review point.", "Send a brief update and assume the dashboard tells the full story."], next: ["aerospace-review", "aerospace-review", "aerospace-reflection"], messages: ["The new team has the context needed to operate within the mission boundary.", "The shared read-back verifies the most safety-critical understanding.", "The incomplete handoff becomes a learning point for the review."] },
    { id: "aerospace-review", title: "Review the mission decision trail", situation: "The immediate phase is complete. The team needs to decide how to learn from the anomaly, constraints, and communication choices.", contexts: ["planning", "technical", "failure"], difficulty: 2, choices: ["Capture the fault evidence and the condition that changed the mission plan.", "Review the systems model and team communication before the next mission.", "Name one simulation or test that would reduce the uncertainty next time."], next: ["aerospace-reflection", "aerospace-reflection", "aerospace-reflection"], messages: ["The mission record connects the decision to its evidence.", "The review links technical learning and team coordination.", "The next test is tied to a specific uncertainty rather than a broad promise."] },
    { id: "aerospace-reflection", title: "Reflect on mission judgment", situation: "Choose how you will carry precision, systems thinking, and team coordination into a future aerospace situation.", contexts: ["planning", "interpersonal", "failure"], difficulty: 2, choices: ["Practice analyzing a small systems anomaly with explicit assumptions.", "Review the decision trail with a mission team or technical peer.", "Ask a mentor for feedback on a high-stakes systems tradeoff."], next: ["aerospace-debrief-practice", "aerospace-debrief-evidence", "aerospace-debrief-feedback"], messages: ["A systems-analysis practice is connected to this mission scenario.", "The team will review the tradeoff with shared evidence.", "A mentor perspective becomes part of the next learning step."] },
  ],
};

export const doctorPhysicianV1Graph = buildDedicatedCareerGraph(doctorSpec);
export const lawyerV1Graph = buildDedicatedCareerGraph(lawyerSpec);
export const entrepreneurStartupFounderV1Graph = buildDedicatedCareerGraph(entrepreneurSpec);
export const aerospaceEngineerAstronautV1Graph = buildDedicatedCareerGraph(aerospaceSpec);
