import { buildDedicatedCareerGraph, type DedicatedCareerGraphSpec } from "./dedicated-career-graph-builder";

type Stage = DedicatedCareerGraphSpec["stages"][number];
const stage = (id: string, title: string, situation: string, choices: Stage["choices"], next: Stage["next"], contexts: Stage["contexts"] = ["technical", "planning", "uncertainty"]): Stage => ({ id, title, situation, choices, next, contexts, difficulty: contexts.includes("time_pressure") || contexts.includes("ethical") ? 3 : 2, messages: ["The next decision now has clearer evidence and an explicit tradeoff.", "The team has a shared next step and review point.", "The unresolved assumption increases the consequence of the next decision."] });

const makeSpec = (id: string, title: string, prefix: string, traits: DedicatedCareerGraphSpec["traits"], stages: Stage[]): DedicatedCareerGraphSpec => ({ id, title, prefix, traits, stages });

const commonClose = (prefix: string): [string, string, string] => [`${prefix}-debrief-practice`, `${prefix}-debrief-evidence`, `${prefix}-debrief-feedback`];

const aiMachineLearningEngineerV1Graph = buildDedicatedCareerGraph(makeSpec("ai-machine-learning-engineer-v1", "AI / machine learning engineer simulation", "ml", ["analytical_thinking", "systems_thinking", "attention_to_detail", "ethical_reasoning", "problem_solving", "communication"], [
  stage("ml-drift", "Model performance drifts", "A model that helps students prioritize practice tasks performs less reliably after a new data source is added.", ["Audit input drift and compare the affected cohort.", "Ask the product and data teams to define the decision risk together.", "Increase the confidence threshold without checking why it changed."], ["ml-evaluation", "ml-impact", "ml-incident"], ["technical", "uncertainty", "time_pressure"]),
  stage("ml-evaluation", "Evaluation hides a tradeoff", "The model improves on an overall metric but weakens for a smaller set of users whose examples are underrepresented.", ["Create a slice-level evaluation and set a release condition.", "Run a bounded experiment with monitoring for the affected group.", "Ship on the overall metric and revisit fairness later."], ["ml-impact", "ml-deployment", "ml-incident"], ["technical", "ethical", "planning"]),
  stage("ml-impact", "Explain a high-impact choice", "A stakeholder wants a simple explanation, but the model has a meaningful limitation that could affect user trust.", ["Explain the supported use, limitation, and human review boundary.", "Invite an accessibility or domain reviewer to challenge the explanation.", "Describe the output as certain so adoption happens faster."], ["ml-deployment", "ml-evaluation", "ml-governance"], ["communication", "ethical", "interpersonal"]),
  stage("ml-incident", "A live prediction needs review", "A surprising prediction reaches a teacher-facing view. The team must protect users and preserve evidence for diagnosis.", ["Pause the affected workflow and record the input-output evidence.", "Route the case to human review while isolating the model behavior.", "Patch the display without documenting the event."], ["ml-governance", "ml-deployment", "ml-reflection"], ["failure", "time_pressure", "technical"]),
  stage("ml-deployment", "Design a safe deployment", "The model is ready for a limited release only if monitoring, ownership, and rollback conditions are explicit.", ["Define monitoring signals and a rollback threshold before release.", "Release to a small group with a scheduled evidence review.", "Release to everyone because the demo deadline is close."], ["ml-governance", "ml-operations", "ml-incident"], ["planning", "technical", "ethical"]),
  stage("ml-governance", "Protect the data boundary", "A growth idea proposes retaining extra sensitive data that is not required for the current model question.", ["Limit collection to the stated purpose and document retention.", "Request a privacy review before changing the training data process.", "Keep all data now and decide on safeguards after the release."], ["ml-operations", "ml-operations", "ml-reflection"], ["ethical", "planning", "time_pressure"]),
  stage("ml-operations", "Hand off the model responsibly", "A new engineer will own the model after launch. They need its assumptions, evaluation limits, and response playbook.", ["Document the data contract, model limits, and incident path.", "Run a handoff review where the incoming owner challenges the assumptions.", "Share only the repository link and let the new owner discover the details."], ["ml-review", "ml-review", "ml-reflection"], ["planning", "interpersonal", "attention_to_detail"]),
  stage("ml-review", "Review what the model taught", "The first release produces useful signals but also new uncertainty about how users interpret the output.", ["Compare observed use with the original hypothesis before the next iteration.", "Collect structured feedback from people affected by the workflow.", "Treat the first release as proof the problem is solved."], ["ml-decision", "ml-decision", "ml-reflection"], ["technical", "interpersonal", "uncertainty"]),
  stage("ml-decision", "Choose the next model investment", "The team can invest in data quality, model complexity, or user-facing explanation. Each solves a different limitation.", ["Prioritize the investment that changes a documented risk.", "Stage two smaller investments with measurable review conditions.", "Choose the most impressive technical option without evidence."], ["ml-reflection", "ml-reflection", "ml-reflection"], ["resource_constraint", "planning", "technical"]),
  stage("ml-reflection", "Reflect on ML engineering judgment", "Choose how you will carry evidence, limitations, and responsible deployment into a future ML project.", ["Practice designing a slice-level evaluation.", "Review the evidence trail with a cross-functional partner.", "Ask a mentor for feedback on a model-risk tradeoff."], commonClose("ml"), ["planning", "ethical", "interpersonal"]),
]));

const productManagerV1Graph = buildDedicatedCareerGraph(makeSpec("product-manager-v1", "Product manager simulation", "pm", ["communication", "collaboration", "systems_thinking", "ownership", "long_term_thinking", "problem_solving"], [
  stage("pm-signal", "A customer problem competes with a launch", "Customer interviews reveal that a key workflow is confusing just as the team prepares a visible launch.", ["Synthesize the interviews and define the user problem precisely.", "Bring design, engineering, and support together around the evidence.", "Keep the launch plan because the roadmap has already been announced."], ["pm-discovery", "pm-alignment", "pm-launch-risk"], ["interpersonal", "uncertainty", "planning"]),
  stage("pm-discovery", "Decide what to learn", "The research points to two possible problems, but the team can validate only one before the next planning decision.", ["Run the smallest test that distinguishes the competing user needs.", "Map the decision each research result would change.", "Add both solutions to the roadmap without testing either."], ["pm-prioritization", "pm-prioritization", "pm-launch-risk"], ["technical", "planning", "resource_constraint"]),
  stage("pm-alignment", "Stakeholders disagree on value", "Sales wants a visible feature, support wants fewer tickets, and engineering warns about reliability debt.", ["Make the tradeoffs visible using user impact and implementation evidence.", "Ask each group to name the assumption behind its request.", "Choose the loudest request so planning can move on."], ["pm-prioritization", "pm-discovery", "pm-commitment"], ["interpersonal", "planning", "uncertainty"]),
  stage("pm-launch-risk", "The release carries a known limitation", "A late issue affects a smaller user group. The team can delay, limit the launch, or proceed with a clear mitigation.", ["Recommend a limited release with monitoring and support coverage.", "Pause the affected path until the team meets a release condition.", "Proceed broadly and explain the issue only if users complain."], ["pm-commitment", "pm-prioritization", "pm-incident"], ["ethical", "time_pressure", "planning"]),
  stage("pm-prioritization", "Prioritize a constrained roadmap", "The roadmap has more valuable requests than the team can safely deliver this cycle.", ["Rank work by customer outcome, evidence, risk, and effort.", "Create a staged plan with one explicit learning checkpoint.", "Promise every request and let engineering sort it out later."], ["pm-commitment", "pm-delivery", "pm-incident"], ["planning", "resource_constraint", "systems_thinking"]),
  stage("pm-commitment", "Make a credible commitment", "A stakeholder asks for certainty on a date while key implementation questions remain open.", ["State the confidence range, dependency, and next decision point.", "Offer a smaller committed outcome with a clear review date.", "Guarantee the broadest scope to preserve stakeholder confidence."], ["pm-delivery", "pm-delivery", "pm-incident"], ["communication", "uncertainty", "ethical"]),
  stage("pm-delivery", "A delivery dependency moves", "An external dependency slips, forcing a decision between scope, quality, and timing.", ["Protect the user-critical path and document the deferred work.", "Coordinate a reset of owners, dependencies, and update cadence.", "Hide the slip until the team has a perfect explanation."], ["pm-measure", "pm-measure", "pm-reflection"], ["planning", "interpersonal", "time_pressure"]),
  stage("pm-incident", "Users report a harmful experience", "The team receives reports that the release creates confusion for a vulnerable user group.", ["Escalate the reports, pause the harmful flow, and name the decision owner.", "Coordinate a response that supports users while evidence is gathered.", "Treat the reports as edge cases because overall metrics are positive."], ["pm-measure", "pm-measure", "pm-reflection"], ["failure", "ethical", "interpersonal"]),
  stage("pm-measure", "Define what success means", "The next iteration needs a measure that captures user outcome rather than only shipping activity.", ["Choose a user-outcome measure and a qualitative check.", "Schedule a review with the teams closest to the customer signal.", "Use launch date alone as the evidence of success."], ["pm-reflection", "pm-reflection", "pm-reflection"], ["planning", "technical", "interpersonal"]),
  stage("pm-reflection", "Reflect on product judgment", "Choose how you will practice evidence-based prioritization and communication in a future product decision.", ["Practice writing a user problem and decision hypothesis.", "Review the roadmap tradeoff with partners using the evidence trail.", "Ask a mentor for feedback on managing a difficult stakeholder commitment."], commonClose("pm"), ["planning", "interpersonal", "failure"]),
]));

const cybersecurityAnalystV1Graph = buildDedicatedCareerGraph(makeSpec("cybersecurity-analyst-v1", "Cybersecurity analyst incident simulation", "cyber", ["attention_to_detail", "problem_solving", "ethical_reasoning", "analytical_thinking", "communication", "long_term_thinking"], [
  stage("cyber-alert", "An alert may be real", "An unusual login pattern appears in a student service. The signal could be a false positive, but access may be at risk.", ["Preserve the event evidence and compare it with normal access patterns.", "Ask operations to validate the account and device context quickly.", "Dismiss the alert because the user has logged in successfully before."], ["cyber-triage", "cyber-containment", "cyber-escalation"], ["technical", "uncertainty", "time_pressure"]),
  stage("cyber-triage", "Scope the exposure", "The initial review finds another related event but cannot yet tell whether sensitive information was accessed.", ["Map the accounts, systems, and time window affected by the event.", "Create a hypothesis log separating known facts from assumptions.", "Search only the most obvious system and conclude the scope is small."], ["cyber-containment", "cyber-investigation", "cyber-escalation"], ["technical", "attention_to_detail", "uncertainty"]),
  stage("cyber-containment", "Contain without destroying evidence", "You can disable access immediately, but an abrupt action may remove useful evidence or interrupt legitimate users.", ["Use a targeted containment step and preserve the forensic trail.", "Coordinate with the service owner on a safe, time-bounded access restriction.", "Reset every account without recording why the action was taken."], ["cyber-investigation", "cyber-communication", "cyber-escalation"], ["technical", "ethical", "time_pressure"]),
  stage("cyber-escalation", "The risk threshold rises", "A new indicator suggests the activity may be connected to a broader compromise.", ["Escalate using the incident criteria and state what is known and unknown.", "Assign parallel roles for evidence, containment, and stakeholder updates.", "Keep the event quiet until you can prove every detail."], ["cyber-investigation", "cyber-communication", "cyber-recovery"], ["failure", "time_pressure", "interpersonal"]),
  stage("cyber-investigation", "Trace the attack path", "The evidence points to a possible configuration weakness and a questionable automated process.", ["Test the suspected path in a safe environment before changing production.", "Review logs across systems to identify the earliest reliable indicator.", "Apply a broad change without confirming whether it addresses the path."], ["cyber-communication", "cyber-recovery", "cyber-recovery"], ["technical", "analytical_thinking", "planning"]),
  stage("cyber-communication", "Communicate the incident responsibly", "Leaders need an update, but sharing too much or too little can create harm and confusion.", ["Provide the current scope, action, uncertainty, and next update time.", "Ask legal or privacy partners to review the communication boundary.", "Describe the incident as resolved before the investigation is complete."], ["cyber-recovery", "cyber-recovery", "cyber-lessons"], ["communication", "ethical", "uncertainty"]),
  stage("cyber-recovery", "Restore a safer service", "The immediate access risk is reduced. The team now needs a recovery plan that protects users and avoids repeating the issue.", ["Define the recovery condition, monitoring, and owner before restoring access.", "Stage restoration with a clear review point after each step.", "Restore everything at once to reduce the time spent on the incident."], ["cyber-lessons", "cyber-lessons", "cyber-reflection"], ["planning", "technical", "resource_constraint"]),
  stage("cyber-lessons", "Turn evidence into prevention", "The team can improve controls, training, or detection. Each would address a different part of the event.", ["Prioritize the control that closes the confirmed path.", "Create a small detection exercise that tests the response process.", "Choose the most visible tool improvement without linking it to the evidence."], ["cyber-handoff", "cyber-handoff", "cyber-reflection"], ["planning", "technical", "long_term_thinking"]),
  stage("cyber-handoff", "Document the decision trail", "The incident is closing, but future responders need a clear record of evidence, actions, and remaining risk.", ["Record the timeline, decisions, and unresolved assumptions.", "Run a short review where responders challenge the conclusion.", "Close the ticket with only the final technical change."], ["cyber-reflection", "cyber-reflection", "cyber-reflection"], ["attention_to_detail", "interpersonal", "planning"]),
  stage("cyber-reflection", "Reflect on security judgment", "Choose how you will practice investigation, containment, and careful communication in a future security situation.", ["Practice scoping an incident from a small evidence set.", "Review the response path with a security peer.", "Ask a mentor for feedback on communicating uncertain incident information."], commonClose("cyber"), ["planning", "failure", "interpersonal"]),
]));

const dataScientistV1Graph = buildDedicatedCareerGraph(makeSpec("data-scientist-v1", "Data scientist investigation simulation", "data", ["analytical_thinking", "attention_to_detail", "problem_solving", "systems_thinking", "communication", "long_term_thinking"], [
  stage("data-question", "A metric changes unexpectedly", "A school-program metric rises sharply after a new reporting process begins. The sponsor wants a recommendation quickly.", ["Clarify the decision the metric should inform before explaining the change.", "Inspect the reporting definition and data lineage with the operations team.", "Assume the program improved because the headline number increased."], ["data-quality", "data-stakeholder", "data-bias"], ["uncertainty", "planning", "technical"]),
  stage("data-quality", "The data has a hidden gap", "A source system changed how it records a subgroup, creating an apparent improvement that may be a measurement artifact.", ["Compare the old and new definitions and quantify the affected records.", "Create a transparent quality note before running any model or forecast.", "Drop the subgroup so the overall trend looks cleaner."], ["data-experiment", "data-stakeholder", "data-bias"], ["technical", "ethical", "attention_to_detail"]),
  stage("data-stakeholder", "A leader asks for a simple answer", "The sponsor asks whether to expand the program, but the evidence supports several possible explanations.", ["Present the likely explanations, limitation, and next decision-changing analysis.", "Ask which outcome and risk the expansion decision must protect.", "Choose the most positive story so the recommendation is easy to approve."], ["data-experiment", "data-experiment", "data-bias"], ["communication", "uncertainty", "ethical"]),
  stage("data-bias", "A comparison could mislead", "A proposed model would rank participants using fields that may reflect unequal access rather than the outcome of interest.", ["Test the proxy risk and define a fairness boundary before using the model.", "Invite a domain reviewer to challenge the target and feature choices.", "Use the fields because they make the prediction more accurate overall."], ["data-experiment", "data-stakeholder", "data-incident"], ["ethical", "technical", "uncertainty"]),
  stage("data-experiment", "Design an informative test", "The team can run one limited analysis before deciding whether to change the program.", ["Choose a comparison that can distinguish the main explanations.", "Predefine the outcome and limitation you will report.", "Run many analyses and report only the most favorable result."], ["data-model", "data-model", "data-incident"], ["analytical_thinking", "planning", "ethical"]),
  stage("data-model", "A model performs unevenly", "The first model helps identify a pattern but performs poorly for an important segment.", ["Inspect segment performance and improve the data or scope the claim.", "Recommend a non-model analysis if it better supports the decision.", "Use the overall score and leave the uneven segment out of the briefing."], ["data-recommendation", "data-recommendation", "data-incident"], ["technical", "ethical", "planning"]),
  stage("data-incident", "A published chart needs correction", "A chart has already been shared, and the team discovers a calculation error that changes the interpretation.", ["Correct the chart, state the impact, and preserve the calculation trail.", "Coordinate a concise update with everyone who relied on the chart.", "Wait to see whether anyone notices the issue."], ["data-recommendation", "data-documentation", "data-reflection"], ["failure", "communication", "ethical"]),
  stage("data-recommendation", "Recommend under uncertainty", "The evidence is stronger, but the program decision still includes uncertainty, cost, and different stakeholder priorities.", ["Recommend the option best supported by the evidence and name its limit.", "Offer a staged decision with a review measure before expansion.", "Present a certainty claim so the decision happens quickly."], ["data-documentation", "data-documentation", "data-reflection"], ["planning", "communication", "uncertainty"]),
  stage("data-documentation", "Make the analysis reusable", "Another analyst will need to reproduce the work and understand which choices could change the conclusion.", ["Document definitions, transformations, and decision limitations.", "Ask a peer to reproduce the critical calculation.", "Save only the final chart because the analysis is complete."], ["data-reflection", "data-reflection", "data-reflection"], ["attention_to_detail", "planning", "interpersonal"]),
  stage("data-reflection", "Reflect on data judgment", "Choose how you will practice data quality, explanation, and responsible recommendation in a future investigation.", ["Practice writing a decision-focused data question.", "Review the evidence trail and assumptions with a peer.", "Ask a mentor for feedback on explaining uncertainty in a recommendation."], commonClose("data"), ["planning", "interpersonal", "failure"]),
]));

const mechanicalEngineerV1Graph = buildDedicatedCareerGraph(makeSpec("mechanical-engineer-v1", "Mechanical engineer design simulation", "mechanical", ["problem_solving", "attention_to_detail", "systems_thinking", "long_term_thinking", "collaboration", "adaptability"], [
  stage("mechanical-test", "A prototype fails a load test", "A prototype bracket bends during a load test shortly before a planned fabrication run.", ["Inspect the test setup, material data, and failure location.", "Bring manufacturing and design together to identify the likely failure path.", "Strengthen the visible area without investigating the load path."], ["mechanical-analysis", "mechanical-manufacturing", "mechanical-safety"], ["technical", "uncertainty", "time_pressure"]),
  stage("mechanical-analysis", "The stress model disagrees", "The simulation predicts more margin than the physical test. One assumption about the boundary condition may be wrong.", ["Isolate the assumption and run a small validation test.", "Compare model and test uncertainty before selecting a design change.", "Trust the model because it is more detailed than the test."], ["mechanical-material", "mechanical-material", "mechanical-safety"], ["technical", "analytical_thinking", "uncertainty"]),
  stage("mechanical-manufacturing", "Fabrication creates a constraint", "The safer design requires a process the student shop cannot perform within the current budget.", ["Modify the design around a validated, available process.", "Map cost, fabrication, and safety tradeoffs with the team.", "Use the unavailable process in the plan and hope the budget changes."], ["mechanical-material", "mechanical-schedule", "mechanical-safety"], ["resource_constraint", "planning", "interpersonal"]),
  stage("mechanical-safety", "A safety margin is questioned", "A reviewer asks whether the design protects users if the load is higher than expected.", ["Define the safety factor and test condition before approval.", "Ask an independent reviewer to challenge the failure assumption.", "Argue that the expected load is unlikely to be exceeded."], ["mechanical-material", "mechanical-analysis", "mechanical-incident"], ["ethical", "technical", "time_pressure"]),
  stage("mechanical-material", "Choose a material tradeoff", "Two materials meet part of the requirement: one is lighter, the other is easier to inspect and repair.", ["Compare performance, inspection, cost, and failure behavior before choosing.", "Build a small sample to test the most uncertain material property.", "Choose the lightest material because the result will look more advanced."], ["mechanical-schedule", "mechanical-schedule", "mechanical-incident"], ["technical", "planning", "resource_constraint"]),
  stage("mechanical-schedule", "A design change affects the schedule", "A revised part improves safety but pushes the fabrication date. The team must decide what to protect.", ["Protect validation and defer a noncritical feature with a documented rationale.", "Create a staged build with inspection after the highest-risk step.", "Skip the next test to keep the original schedule."], ["mechanical-build", "mechanical-build", "mechanical-incident"], ["planning", "time_pressure", "ethical"]),
  stage("mechanical-incident", "A build issue appears", "During assembly, a part does not fit as the drawing predicted. The team must avoid turning a local issue into a hidden system failure.", ["Pause assembly, measure the mismatch, and update the drawing record.", "Coordinate a containment fix while preserving the original part for review.", "Force the part into place so the demonstration can continue."], ["mechanical-build", "mechanical-review", "mechanical-reflection"], ["failure", "technical", "time_pressure"]),
  stage("mechanical-build", "Plan a reliable build", "The design is ready for a controlled build if roles, tolerances, and inspection points are visible.", ["Define the critical dimensions and inspection checkpoint for each handoff.", "Assign an owner for build quality and a review before use.", "Let each person interpret the drawing as they build."], ["mechanical-review", "mechanical-review", "mechanical-reflection"], ["planning", "attention_to_detail", "interpersonal"]),
  stage("mechanical-review", "Review the physical system", "The prototype works in the current test. The team needs to decide what evidence supports the next iteration.", ["Capture measurements, limitations, and the next test condition.", "Review the build and failure trail with the people who fabricated it.", "Treat the first successful test as proof the design is finished."], ["mechanical-reflection", "mechanical-reflection", "mechanical-reflection"], ["technical", "failure", "planning"]),
  stage("mechanical-reflection", "Reflect on engineering judgment", "Choose how you will practice test-driven design, safety, and collaboration in a future mechanical project.", ["Practice planning a small load-test with a clear condition.", "Review the tradeoffs with a fabrication or engineering peer.", "Ask a mentor for feedback on a safety-versus-schedule decision."], commonClose("mechanical"), ["planning", "interpersonal", "failure"]),
]));

export { aiMachineLearningEngineerV1Graph, productManagerV1Graph, cybersecurityAnalystV1Graph, dataScientistV1Graph, mechanicalEngineerV1Graph };
