import { buildDedicatedCareerGraph, type DedicatedCareerGraphSpec } from "./dedicated-career-graph-builder";

type Entry = [string, string, [string, string, string]];
const routes = (prefix: string): [string, string, string][] => [[`${prefix}-two`, `${prefix}-three`, `${prefix}-four`], [`${prefix}-five`, `${prefix}-five`, `${prefix}-six`], [`${prefix}-five`, `${prefix}-six`, `${prefix}-seven`], [`${prefix}-six`, `${prefix}-seven`, `${prefix}-eight`], [`${prefix}-seven`, `${prefix}-eight`, `${prefix}-nine`], [`${prefix}-eight`, `${prefix}-nine`, `${prefix}-ten`], [`${prefix}-nine`, `${prefix}-ten`, `${prefix}-ten`], [`${prefix}-ten`, `${prefix}-ten`, `${prefix}-ten`], [`${prefix}-ten`, `${prefix}-ten`, `${prefix}-ten`], [`${prefix}-debrief-practice`, `${prefix}-debrief-evidence`, `${prefix}-debrief-feedback`]];
const graph = (id: string, title: string, prefix: string, traits: DedicatedCareerGraphSpec["traits"], entries: Entry[]) => buildDedicatedCareerGraph({ id, title, prefix, traits, stages: entries.map(([title, situation, choices], index) => ({ id: `${prefix}-${["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"][index]}`, title, situation, choices, next: routes(prefix)[index]!, contexts: index === 0 || index === 3 ? ["uncertainty", "time_pressure", "interpersonal"] : index === 4 || index === 6 ? ["ethical", "planning", "resource_constraint"] : ["technical", "planning", "interpersonal"], difficulty: index === 0 || index === 3 || index === 4 ? 3 : 2, messages: ["The next professional decision has clearer evidence and a visible consequence.", "The people responsible now share a reviewable next step.", "The unreviewed assumption increases the risk in the next situation."] })) });

export const architectV1Graph = graph("architect-v1", "Architect design simulation", "architect", ["systems_thinking", "communication", "ethical_reasoning", "long_term_thinking", "attention_to_detail", "collaboration"], [
  ["A site constraint changes the brief", "A community site has limited access, a tight budget, and a client request that conflicts with inclusive circulation.", ["Map access, safety, and client needs before changing the plan.", "Invite the client and user representative into a design review.", "Keep the original circulation because the rendering is already approved."]],
  ["Read the site", "Sun, drainage, and neighboring use reveal that the first massing idea may create a difficult public edge.", ["Test two massing options against the site evidence.", "Document the environmental constraint for the next review.", "Treat the site issue as something landscaping can solve later."]],
  ["Design for different users", "A mobility advocate identifies a route that works on paper but not for many real users.", ["Revise the route with accessibility as a design condition.", "Ask the advocate to challenge the revised circulation.", "Preserve the route and add a separate alternative entrance."]],
  ["A safety question emerges", "The structural concept and public gathering use create an unresolved egress concern before permit review.", ["Pause for a code and safety review with the consultant.", "Define the exact evidence needed for the next design decision.", "Assume the permit reviewer will solve the egress detail."]],
  ["Balance materials and climate", "The client prefers a material with a high maintenance burden in the local climate.", ["Compare durability, repair, cost, and embodied impact.", "Propose a staged mock-up before commitment.", "Select the material because it best matches the visual reference."]],
  ["Coordinate the consultant set", "Mechanical, structural, and landscape drawings now conflict at a critical public space.", ["Run a coordinated clash review with decision owners.", "Set a shared revision checkpoint before drawing issue.", "Let each consultant resolve their part independently."]],
  ["Choose what to protect", "The budget requires reducing scope, but one reduction would weaken an inclusive and safe use condition.", ["Protect the essential public-use condition and defer a cosmetic item.", "Explain the tradeoff with user impact and cost evidence.", "Reduce the access feature because it serves fewer visitors."]],
  ["Prepare a construction decision", "A contractor proposes a substitution that may change maintenance and performance.", ["Request product evidence and test the substitution against requirements.", "Ask the construction team to name the long-term owner impact.", "Approve quickly to avoid a schedule discussion."]],
  ["Document the design rationale", "The project moves forward only if future reviewers can see why key tradeoffs were chosen.", ["Record the user, site, and safety rationale in the decision log.", "Review the decision set with the design team.", "Keep only the final drawings and remove the alternatives."]],
  ["Reflect on design judgment", "Choose how you will carry site evidence, inclusive design, and coordination into the next project.", ["Practice an access-focused site observation.", "Review the tradeoffs with a design peer.", "Ask a mentor for feedback on a client-versus-user decision."]],
]);

export const uxProductDesignerV1Graph = graph("ux-product-designer-v1", "UX / product designer simulation", "ux", ["communication", "collaboration", "ethical_reasoning", "adaptability", "attention_to_detail", "problem_solving"], [
  ["A usability session changes the brief", "A student user cannot complete a key flow without help, while the product team expects to launch next week.", ["Observe the task failure and ask what the user expected.", "Bring the researcher and engineer into a short evidence review.", "Explain the issue as user error and preserve the flow."]],
  ["Synthesize conflicting feedback", "Some users like the new interface while others cannot find a required action.", ["Group the evidence by task and severity.", "Test a focused alternative with representative users.", "Choose the version preferred by the loudest stakeholder."]],
  ["Design for access", "A screen-reader user identifies a missing relationship between controls and feedback.", ["Treat accessibility as a release condition and revise the interaction.", "Ask an accessibility reviewer to test the new pattern.", "Add a text note without changing the control behavior."]],
  ["A dark pattern is proposed", "A growth request would make cancellation difficult while improving a short-term metric.", ["Name the user trust risk and propose a transparent alternative.", "Ask the team to evaluate the metric against user harm.", "Use the pattern because competitors already do."]],
  ["Choose a prototype", "The team can validate navigation, content clarity, or error recovery before the next build.", ["Prototype the highest-risk user task first.", "Set a measurable learning question for the session.", "Polish visual details before testing the task flow."]],
  ["Work through engineering limits", "The preferred interaction has a technical constraint that affects performance on older devices.", ["Map the user outcome and technical constraint before simplifying.", "Co-design a reversible alternative with engineering.", "Keep the interaction and hope the performance issue is minor."]],
  ["Prepare a design handoff", "Engineering needs states, behaviors, and exceptions to implement the experience reliably.", ["Document interactions, error states, and accessibility behavior.", "Walk through the key task with the implementing engineer.", "Share only static visuals and answer questions later."]],
  ["Review product impact", "The first build works for the main path but a secondary user group has a different mental model.", ["Compare task success across the groups before the next decision.", "Collect a short qualitative explanation from affected users.", "Treat the secondary path as an edge case."]],
  ["Make the next change visible", "The team needs a decision trail for what changed after research and why.", ["Record the evidence, choice, and open question.", "Review the decision with research and product partners.", "Keep the change informal to stay fast."]],
  ["Reflect on design judgment", "Choose how you will carry user evidence, access, and collaboration into the next design decision.", ["Practice a focused usability observation.", "Review the evidence trail with a partner.", "Ask a mentor for feedback on an ethical design tradeoff."]],
]);

export const financialAnalystV1Graph = graph("financial-analyst-v1", "Financial analyst simulation", "finance", ["analytical_thinking", "attention_to_detail", "long_term_thinking", "ethical_reasoning", "communication", "systems_thinking"], [
  ["A forecast misses its target", "A quarterly forecast changes after a supplier update, and leaders want a recommendation before the board packet closes.", ["Reconcile assumptions, source documents, and the changed driver.", "Ask operations to explain which assumption is most uncertain.", "Keep the original forecast to avoid a difficult update."]],
  ["Find the driver", "Revenue and cost signals move in opposite directions across two business lines.", ["Separate volume, price, timing, and one-time effects.", "Build a sensitivity range for the decision makers.", "Use the overall total because the segments are too detailed."]],
  ["A client asks for certainty", "A leader asks whether the company can fund a new initiative with no downside.", ["Explain the range, key assumption, and risk condition.", "Offer a staged funding option with review points.", "Present the best-case value as the expected result."]],
  ["A disclosure concern appears", "A draft summary omits a material risk that makes the recommendation less attractive.", ["Include the risk and explain its decision relevance.", "Ask a senior reviewer to challenge the disclosure boundary.", "Leave it out because the risk is not guaranteed."]],
  ["Choose an investment lens", "The team can compare return, resilience, and cash impact, but no option leads on all three.", ["Compare each option against explicit decision criteria.", "Model the downside case before recommending.", "Choose the highest return without testing the assumptions."]],
  ["The market moves", "A late market change invalidates part of the earlier scenario analysis.", ["Update the scenario and identify what decision changes.", "Communicate the impact and uncertainty immediately.", "Wait for the market to return to the expected range."]],
  ["Protect the controls", "A fast close process makes it tempting to bypass a review that usually catches classification errors.", ["Keep the control and reassign capacity to meet the deadline.", "Document a temporary review plan with an accountable owner.", "Bypass the review because the difference looks small."]],
  ["Brief decision makers", "Leaders need a concise briefing that explains value, risk, and what would change the recommendation.", ["Present options with assumptions and decision triggers.", "Invite questions on the downside case before finalizing.", "Show only the recommended option to keep the meeting short."]],
  ["Preserve the audit trail", "The recommendation will be revisited later, so sources and reasoning must be usable.", ["Record source assumptions and model limitations.", "Ask a peer to reproduce the critical calculation.", "Save only the final presentation."]],
  ["Reflect on financial judgment", "Choose how you will practice careful analysis, communication, and ethical disclosure.", ["Practice building a sensitivity table.", "Review the reasoning with a finance peer.", "Ask a mentor for feedback on a disclosure tradeoff."]],
]);

export const environmentalScientistV1Graph = graph("environmental-scientist-v1", "Environmental scientist simulation", "environment", ["systems_thinking", "ethical_reasoning", "long_term_thinking", "communication", "problem_solving", "adaptability"], [
  ["Field observations challenge a plan", "A restoration plot shows different conditions than expected before a community stewardship meeting.", ["Verify the observations and map the local system factors.", "Invite community and field partners into the evidence review.", "Continue the plan because the original model was approved."]],
  ["Separate signal from season", "Recent rain may explain the observation, but a longer-term pattern is also possible.", ["Compare sites, seasons, and measurement methods.", "Define the next observation that would change the action.", "Treat one recent sample as enough evidence."]],
  ["A community impact is raised", "A mitigation option could improve habitat while limiting access to a place used by local residents.", ["Map ecological benefit and community burden before recommending.", "Ask affected residents to challenge the proposed mitigation.", "Prioritize the ecological metric without discussing access."]],
  ["A contamination risk appears", "A field result may require a faster protective response than the original research schedule allowed.", ["Escalate the risk and define an immediate safe boundary.", "Coordinate sampling and communication roles in parallel.", "Wait for the full report before telling anyone."]],
  ["Choose a mitigation", "The team can restore, monitor, or limit activity, each with different cost and uncertainty.", ["Choose the action best matched to evidence and reversible learning.", "Stage a smaller intervention with a review condition.", "Select the most visible action without measuring likely effect."]],
  ["Plan the monitoring", "The next season will matter only if measurements are consistent and meaningful.", ["Set an observation plan tied to the decision question.", "Assign field roles and quality checks before collection.", "Collect every possible measure without a review plan."]],
  ["Communicate an uncertain finding", "A public meeting needs a clear explanation without overstating what the data shows.", ["Explain the evidence, limitation, and next observation.", "Invite questions about local experience and impact.", "Present the preliminary result as a final conclusion."]],
  ["Coordinate a response", "Different agencies and partners have overlapping responsibility for the next action.", ["Make responsibilities and escalation conditions explicit.", "Create a short joint review before implementation.", "Let each group act independently."]],
  ["Document environmental learning", "Future stewards need to know why the plan changed and what remains uncertain.", ["Record observations, choices, and open ecological questions.", "Review the record with field and community partners.", "Keep only the final map."]],
  ["Reflect on systems stewardship", "Choose how you will carry evidence, community impact, and long-term systems thinking forward.", ["Practice planning a field observation.", "Review the system tradeoff with a peer.", "Ask a mentor for feedback on an ecology-community decision."]],
]);

export const researchScientistV1Graph = graph("research-scientist-v1", "Research scientist simulation", "research", ["analytical_thinking", "attention_to_detail", "long_term_thinking", "problem_solving", "ethical_reasoning", "systems_thinking"], [
  ["A result challenges the hypothesis", "A replicated measurement differs from the original finding shortly before a student research presentation.", ["Audit the method, materials, and measurement record.", "Ask a lab partner to independently inspect the anomaly.", "Use the original result because it supports the hypothesis."]],
  ["Test the alternative explanation", "Two explanations now fit the observation, but the team can run only one additional experiment.", ["Choose the experiment that best distinguishes the explanations.", "Predefine what outcome would change the conclusion.", "Run the easiest experiment even if it cannot resolve the question."]],
  ["A reproducibility concern appears", "A key condition was not recorded consistently across the first trials.", ["Repeat the trials with a controlled protocol.", "Document the limitation before interpreting the finding.", "Average the trials and ignore the missing condition."]],
  ["An ethics boundary is relevant", "A proposed data source could speed the study but lacks clear consent for this use.", ["Stop and confirm the consent and data-use boundary.", "Ask an ethics or teacher reviewer for guidance.", "Use the source because no one has objected yet."]],
  ["Choose the claim", "The evidence supports a smaller claim than the team originally hoped to make.", ["Narrow the claim to what the evidence can support.", "Present a staged conclusion with a next research question.", "Keep the broad claim and mention uncertainty in a footnote."]],
  ["Plan peer review", "A reviewer asks for a transparent explanation of choices that could affect the result.", ["Share methods, exclusions, and limitation openly.", "Ask a peer to reproduce the key analysis.", "Provide only the summary to keep the review simple."]],
  ["Respond to a null result", "The next trial does not show the expected effect, but it still contains useful information.", ["Record the null result and compare it to the hypothesis.", "Revise the experiment based on the failure evidence.", "Exclude the result because it is inconvenient."]],
  ["Manage a resource constraint", "Time and materials allow either one deeper replication or a broader exploratory measurement.", ["Fund the step that most changes confidence in the conclusion.", "Set a bounded exploratory test with a review point.", "Choose the result most likely to look impressive."]],
  ["Preserve the research record", "Future researchers need a record that distinguishes observation, interpretation, and open question.", ["Document the protocol, data trail, and reasoning.", "Review the record with the research team.", "Keep only the polished final figure."]],
  ["Reflect on scientific judgment", "Choose how you will carry curiosity, rigor, and integrity into a future investigation.", ["Practice writing a falsifiable research question.", "Review the evidence trail with a peer.", "Ask a mentor for feedback on a difficult interpretation choice."]],
]);
