import type { ConsequenceDefinition, DecisionDefinition, SimulationGraph, TraitSignal } from "../contracts";

type CareerSimulationSpec = {
  id: string; title: string; prefix: string; opening: string; evidence: string; impact: string; pressure: string; outcome: string;
  work: string; team: string; evidenceLabel: string; stakeholder: string;
  openingChoices: [string, string, string]; evidenceChoices: [string, string, string]; impactChoices: [string, string, string]; pressureChoices: [string, string, string];
};

const signal = (trait: TraitSignal["trait"], context: TraitSignal["context"], weight: 1 | 2 | 3 = 1): TraitSignal => ({ trait, direction: 1, weight, context });
const caution = (trait: TraitSignal["trait"], context: TraitSignal["context"], weight: 1 | 2 | 3 = 1): TraitSignal => ({ trait, direction: -1, weight, context });
const consequence = (id: string, message: string, kind: ConsequenceDefinition["kind"]): ConsequenceDefinition[] => [{ id, message, kind }];
const decision = (id: string, label: string, signals: TraitSignal[], next: string, message: string, kind: ConsequenceDefinition["kind"], statePatch?: DecisionDefinition["statePatch"]): DecisionDefinition => ({ id, label, signals, next, consequences: consequence(id, message, kind), statePatch });

function buildExpandedCareerGraph(spec: CareerSimulationSpec): SimulationGraph {
  const id = (stage: string) => `${spec.prefix}-${stage}`;
  return { id: spec.id, title: spec.title, startNodeId: id("brief"), nodes: {
    [id("brief")]: { id: id("brief"), title: "A decision needs evidence", situation: spec.opening, contexts: ["uncertainty", "time_pressure", "interpersonal"], difficulty: 2, decisions: [
      decision("inspect-evidence", spec.openingChoices[0], [signal("analytical_thinking", "uncertainty", 2), signal("attention_to_detail", "technical")], id("evidence"), `The ${spec.team} has a clearer evidence question, although the decision window is tighter.`, "learning", { timePressure: 1, discoveredInformation: [`${spec.prefix}-evidence`] }),
      decision("invite-stakeholder", spec.openingChoices[1], [signal("collaboration", "interpersonal", 2), signal("ethical_reasoning", "ethical")], id("impact"), `A ${spec.stakeholder} perspective is now part of the next choice.`, "team", { teamTrust: 1 }),
      decision("carry-assumption", spec.openingChoices[2], [signal("adaptability", "time_pressure"), caution("long_term_thinking", "planning", 2)], id("pressure"), "Momentum is preserved, but an assumption remains visible for the next decision.", "caution", { riskExposure: 1, unresolvedEvents: [`${spec.prefix}-unreviewed-assumption`] }),
    ] },
    [id("evidence")]: { id: id("evidence"), title: "The evidence changes the question", situation: spec.evidence, contexts: ["technical", "uncertainty", "planning"], difficulty: 2, decisions: [
      decision("test-small", spec.evidenceChoices[0], [signal("problem_solving", "technical", 2), signal("systems_thinking", "planning")], id("tradeoff"), "A smaller test makes the next trade-off easier to explain.", "learning", { projectHealth: 1 }),
      decision("define-condition", spec.evidenceChoices[1], [signal("attention_to_detail", "technical", 2), signal("long_term_thinking", "planning")], id("tradeoff"), `The ${spec.team} now has a shared condition for moving forward.`, "progress", { projectHealth: 1 }),
      decision("narrow-scope", spec.evidenceChoices[2], [signal("adaptability", "resource_constraint", 2), signal("ownership", "planning")], id("tradeoff"), "The work is now smaller and more testable without claiming the uncertainty is gone.", "progress", { projectHealth: 1 }),
    ] },
    [id("impact")]: { id: id("impact"), title: "Impact is part of the decision", situation: spec.impact, contexts: ["interpersonal", "ethical", "planning"], difficulty: 2, decisions: [
      decision("map-impact", spec.impactChoices[0], [signal("systems_thinking", "planning", 2), signal("ethical_reasoning", "ethical")], id("tradeoff"), "The recommendation can name both likely impact and open uncertainty.", "learning", { teamTrust: 1 }),
      decision("seek-review", spec.impactChoices[1], [signal("communication", "interpersonal", 2), signal("adaptability", "uncertainty")], id("tradeoff"), "A fresh review is available before the recommendation is made.", "team", { timePressure: 1, teamTrust: 1 }),
      decision("state-priority", spec.impactChoices[2], [signal("ownership", "planning"), signal("communication", "interpersonal", 2)], id("tradeoff"), "The group has a clearer priority and a record of what needs later review.", "team", { teamTrust: 1 }),
    ] },
    [id("pressure")]: { id: id("pressure"), title: "Time pressure reveals a trade-off", situation: spec.pressure, contexts: ["time_pressure", "uncertainty", "resource_constraint"], difficulty: 3, decisions: [
      decision("surface-risk", spec.pressureChoices[0], [signal("communication", "time_pressure", 2), signal("ownership", "planning")], id("tradeoff"), "The unresolved risk is visible to the people who need to decide how to proceed.", "progress", { teamTrust: 1 }),
      decision("protect-core", spec.pressureChoices[1], [signal("attention_to_detail", "technical", 2), signal("adaptability", "time_pressure")], id("tradeoff"), "The team reduced exposure while protecting a usable core path.", "progress", { projectHealth: 1, riskExposure: -1 }),
      decision("rush", spec.pressureChoices[2], [signal("ownership", "time_pressure"), caution("ethical_reasoning", "ethical", 2)], id("tradeoff"), "The deadline is protected, but more uncertainty moves into the next stage.", "caution", { riskExposure: 2, projectHealth: -1 }),
    ] },
    [id("tradeoff")]: { id: id("tradeoff"), title: "Choose what the work protects", situation: `The ${spec.team} has enough information to make a bounded choice about the ${spec.work}. The remaining question is how to balance an immediate result with learning for the next cycle.`, contexts: ["planning", "execution", "ethical"], difficulty: 3, decisions: [
      decision("recommend-evidence", `Recommend the option that best matches the available ${spec.evidenceLabel} and name its limitation.`, [signal("analytical_thinking", "planning", 2), signal("ethical_reasoning", "ethical")], id("plan"), "The recommendation stays connected to both evidence and its limits.", "learning", { projectHealth: 1 }),
      decision("stage-work", `Recommend a staged ${spec.work} decision with a review point before committing further.`, [signal("long_term_thinking", "planning", 2), signal("systems_thinking", "execution")], id("plan"), "The plan includes a review point rather than a one-way commitment.", "progress", { riskExposure: -1 }),
      decision("align-team", `Coordinate a short alignment conversation before the ${spec.team} begins work.`, [signal("collaboration", "interpersonal", 2), signal("communication", "planning")], id("plan"), "Dependencies and concerns are clearer before the work begins.", "team", { teamTrust: 1 }),
    ] },
    [id("plan")]: { id: id("plan"), title: "Make the next step observable", situation: `The ${spec.team} now needs an implementation plan that makes ownership, validation, and communication visible.`, contexts: ["execution", "planning", "interpersonal"], difficulty: 2, decisions: [
      decision("assign-checkpoint", "Assign an owner and a measurable review checkpoint.", [signal("ownership", "execution", 2), signal("attention_to_detail", "planning")], id("outcome"), "The team has a named review point for learning from the outcome.", "progress", { projectHealth: 1 }),
      decision("coordinate-handoff", "Make dependencies explicit and coordinate a responsible handoff.", [signal("collaboration", "interpersonal", 2), signal("systems_thinking", "planning")], id("outcome"), "The team has a clearer shared picture of the work ahead.", "team", { teamTrust: 1 }),
      decision("start-small", "Start the smallest safe piece of work and report back with evidence.", [signal("adaptability", "resource_constraint", 2), signal("problem_solving", "execution")], id("outcome"), "The next step is small enough to learn from without overcommitting.", "learning", { projectHealth: 1 }),
    ] },
    [id("outcome")]: { id: id("outcome"), title: "Close the learning loop", situation: spec.outcome, contexts: ["failure", "planning", "interpersonal"], difficulty: 2, decisions: [
      decision("capture-learning", "Capture the evidence, rationale, and one question for next time.", [signal("long_term_thinking", "planning", 2), signal("analytical_thinking", "failure")], id("reflection"), "The team has a reusable record for a similar future decision.", "learning", { projectHealth: 1 }),
      decision("request-feedback", "Request feedback on how the team communicated the trade-off.", [signal("communication", "interpersonal", 2), signal("adaptability", "planning")], id("reflection"), "The team created a chance to improve difficult conversations next time.", "team", { teamTrust: 1 }),
      decision("name-follow-up", "Name one follow-up review before moving to the next priority.", [signal("ownership", "planning"), signal("long_term_thinking", "planning")], id("reflection"), "The learning work has a concrete review rather than an open-ended intention.", "progress", { unresolvedEvents: [] }),
    ] },
    [id("reflection")]: { id: id("reflection"), title: "Reflect before the next cycle", situation: `Before the ${spec.team} closes this work, there is time to decide what communication or evidence practice should change in the next ${spec.work}.`, contexts: ["planning", "interpersonal", "failure"], difficulty: 2, decisions: [
      decision("name-pattern", "Name one decision pattern worth practicing in the next cycle.", [signal("long_term_thinking", "planning", 2), signal("ownership", "execution")], id("review"), "A specific practice opportunity is now connected to this experience.", "progress"),
      decision("review-tradeoff", "Review the trade-off with the team before deciding what to change next.", [signal("analytical_thinking", "planning"), signal("collaboration", "interpersonal", 2)], id("review"), "The team will revisit the result with shared evidence.", "learning"),
      decision("seek-mentor", "Ask a teacher, mentor, or reviewer for feedback on the trade-off.", [signal("communication", "interpersonal"), signal("adaptability", "planning")], id("review"), "An additional perspective is now part of the team’s learning plan.", "team"),
    ] },
    [id("review")]: { id: id("review"), title: "Choose a review method", situation: `The ${spec.team} can now make its next learning step observable rather than leaving the reflection as an intention.`, contexts: ["planning", "execution", "resource_constraint"], difficulty: 2, decisions: [
      decision("set-measure", "Set one simple measure that would show whether the next change helped.", [signal("attention_to_detail", "planning", 2), signal("systems_thinking", "execution")], id("learning"), "The next learning move now has an observable signal to review.", "progress"),
      decision("schedule-check", "Schedule a short review with the people who worked on the decision.", [signal("collaboration", "interpersonal", 2), signal("ownership", "planning")], id("learning"), "A shared checkpoint will keep the follow-up visible.", "team"),
      decision("make-small-test", "Choose the smallest test that could change the next decision.", [signal("problem_solving", "execution", 2), signal("adaptability", "resource_constraint")], id("learning"), "The team has a bounded test rather than a broad promise to improve.", "learning"),
    ] },
    [id("learning")]: { id: id("learning"), title: "Choose the next learning move", situation: "One final choice will determine how this experience is carried into the next project or work situation.", contexts: ["planning", "execution"], difficulty: 2, decisions: [
      decision("practice-skill", "Practice one decision skill through a small, evidence-focused project.", [signal("ownership", "execution"), signal("long_term_thinking", "planning")], id("debrief-practice"), "A specific learning move is now connected to the experience.", "progress"),
      decision("review-evidence", "Review the outcome with the team before deciding what to change next.", [signal("analytical_thinking", "planning"), signal("collaboration", "interpersonal")], id("debrief-evidence"), "The team will revisit the outcome with shared evidence.", "learning"),
      decision("seek-feedback", "Ask for feedback on how the trade-off and communication were handled.", [signal("communication", "interpersonal"), signal("adaptability", "planning")], id("debrief-feedback"), "An external perspective is part of the next learning step.", "team"),
    ] },
    [id("debrief-practice")]: { id: id("debrief-practice"), title: "Practice-oriented close", situation: "This scenario closes with a small practice move named for a future work situation. It is a scenario outcome, not an assessment of you.", contexts: ["planning"], difficulty: 1, decisions: [], terminal: true, terminalOutcome: "practice_next_step" },
    [id("debrief-evidence")]: { id: id("debrief-evidence"), title: "Evidence-review close", situation: "This scenario closes with a shared-evidence review before the next change. It is a scenario outcome, not an assessment of you.", contexts: ["planning"], difficulty: 1, decisions: [], terminal: true, terminalOutcome: "evidence_review" },
    [id("debrief-feedback")]: { id: id("debrief-feedback"), title: "Feedback-oriented close", situation: "This scenario closes with an invitation for another perspective on the trade-off. It is a scenario outcome, not an assessment of you.", contexts: ["planning"], difficulty: 1, decisions: [], terminal: true, terminalOutcome: "feedback_conversation" },
  } };
}

const specs: CareerSimulationSpec[] = [
  { id: "engineering-design-v1", title: "Engineering & built systems simulation", prefix: "engineering", opening: "During a student engineering design review, a prototype load test reveals a safety concern close to a demonstration. The team needs to decide how to learn before changing the design.", evidence: "The test notes show that one component behaves differently when the system is used near its intended limit.", impact: "A teammate asks how the design decision could affect users, maintainers, and the people relying on the system.", pressure: "The demonstration window is close, and the team must recommend a safe next move.", outcome: "The team documents a practical, safety-aware design path and a follow-up test.", work: "design", team: "engineering team", evidenceLabel: "test evidence", stakeholder: "user and maintainer", openingChoices: ["Inspect the load-test notes and isolate the component before changing the design.", "Invite a teammate to map who could be affected by the design change.", "Keep the current prototype plan and record the safety assumption for a later review."], evidenceChoices: ["Build a small bench test for the affected component and compare the outcome.", "Define a safety condition the design must meet before the team proceeds.", "Narrow the prototype scope so the team can validate the most important function."], impactChoices: ["Map safety, reliability, and maintenance trade-offs before recommending a design path.", "Ask someone outside the build team to review the user and maintenance implications.", "State the current design priority and invite a focused challenge to it."], pressureChoices: ["Surface the unresolved safety assumption to the people accountable for the demonstration.", "Protect the validated core design and defer the uncertain component with a rationale.", "Move ahead without another safety review so the demonstration date is preserved."] },
  { id: "scientific-research-v1", title: "Scientific research investigation simulation", prefix: "research", opening: "In a student research investigation, an unexpected pattern appears shortly before a group presentation. The team must decide what evidence can support a responsible conclusion.", evidence: "The latest observations suggest a possible alternative explanation that the original method did not test.", impact: "A teammate asks how the conclusion could affect other students who may build on this result.", pressure: "The presentation is close, and the team needs a transparent recommendation about the finding.", outcome: "The team records a careful conclusion, its limitations, and the next research question.", work: "investigation", team: "research team", evidenceLabel: "observations", stakeholder: "future researcher", openingChoices: ["Review the observation log and method notes before changing the conclusion.", "Invite a teammate to identify who could rely on the research conclusion.", "Keep the original conclusion and record the alternative explanation for later."], evidenceChoices: ["Run a smaller comparison measurement that could distinguish the explanations.", "Define a replication condition before the team treats the finding as reliable.", "Narrow the claim so it matches what the current observations can support."], impactChoices: ["Map the possible benefit, limitation, and open question before presenting the finding.", "Ask a teacher or lab peer for a short review of the interpretation.", "State the evidence threshold for the current claim and invite a challenge."], pressureChoices: ["Surface the alternative explanation before the presentation recommendation is made.", "Protect the validated observation and defer the uncertain interpretation with a rationale.", "Present the strongest claim without another review so the presentation remains simple."] },
  { id: "public-policy-v1", title: "Public policy & civic systems simulation", prefix: "policy", opening: "A student civic team receives new community feedback that challenges an assumption in a proposed local policy. The group must decide how to revise its recommendation responsibly.", evidence: "The feedback indicates that the proposal may affect one community group differently than the team expected.", impact: "A teammate asks the group to make benefits, burdens, and implementation limits visible before speaking publicly.", pressure: "A council-style presentation is approaching, and the team needs a clear recommendation.", outcome: "The team documents a community-aware policy option and a question for continued consultation.", work: "policy proposal", team: "civic team", evidenceLabel: "community feedback", stakeholder: "community member", openingChoices: ["Review the community feedback before revising the policy proposal.", "Invite a teammate to identify who could carry a burden or benefit from the policy.", "Keep the current recommendation and record the feedback for a later consultation."], evidenceChoices: ["Test one revised policy option against the feedback and compare the likely effects.", "Define an implementation condition before the team recommends the proposal.", "Narrow the proposal so the group can protect the most important community outcome."], impactChoices: ["Map the benefits, burdens, and open questions before recommending a policy path.", "Ask a community-informed reviewer for a short response to the recommendation.", "State the current public priority and invite a focused challenge to it."], pressureChoices: ["Surface the unresolved community concern to the people making the recommendation.", "Protect the validated core policy idea and defer the uncertain element with a rationale.", "Move ahead without another consultation so the presentation date is preserved."] },
  { id: "education-learning-v1", title: "Education & learning design simulation", prefix: "education", opening: "A student teaching team learns that a learning activity is not working equally well for every participant. The group needs to decide what to learn before revising it.", evidence: "The feedback suggests that part of the activity assumes prior knowledge that some learners have not had.", impact: "A teammate asks how the next change could support learners while remaining practical for an educator to use.", pressure: "A classroom pilot is close, and the team needs a clear, testable next step.", outcome: "The team documents a learner-centered adjustment and a way to review the result.", work: "learning activity", team: "learning design team", evidenceLabel: "learner feedback", stakeholder: "learner and educator", openingChoices: ["Review the learner feedback and activity steps before changing the design.", "Invite a teammate to identify which learners could be affected by the assumption.", "Keep the current activity plan and record the learning assumption for later review."], evidenceChoices: ["Test a small scaffold in the activity and compare the learner experience.", "Define an accessibility and understanding condition before the team proceeds.", "Narrow the activity scope so the team can validate the most important learning outcome."], impactChoices: ["Map learner benefit, educator effort, and open questions before recommending a change.", "Ask an educator or learner outside the team for a short review of the change.", "State the current learning priority and invite a focused challenge to it."], pressureChoices: ["Surface the unresolved access concern before the classroom pilot decision is made.", "Protect the validated learning core and defer the uncertain element with a rationale.", "Move ahead without another learner review so the classroom date is preserved."] },
  { id: "environmental-systems-v1", title: "Environmental & earth systems simulation", prefix: "environment", opening: "A student environmental team receives field observations that challenge an assumption in its restoration plan. The group must decide what evidence should guide the next action.", evidence: "The observations suggest that one part of the local system may respond differently across seasons or locations.", impact: "A teammate asks the group to make ecological, community, and resource effects visible before choosing a path.", pressure: "A stewardship meeting is close, and the team needs a transparent recommendation.", outcome: "The team documents a systems-aware action and a follow-up observation plan.", work: "stewardship plan", team: "environmental team", evidenceLabel: "field observations", stakeholder: "community and ecosystem partner", openingChoices: ["Review the field observations before changing the stewardship plan.", "Invite a teammate to identify who and what could be affected by the plan.", "Keep the current stewardship plan and record the ecological assumption for later review."], evidenceChoices: ["Test one small restoration adjustment and compare the field observations.", "Define an observation condition before the team expands the stewardship action.", "Narrow the plan so the team can protect the most important ecological outcome."], impactChoices: ["Map ecological benefit, community impact, and open questions before recommending a path.", "Ask a local or scientific reviewer for a short response to the recommendation.", "State the current stewardship priority and invite a focused challenge to it."], pressureChoices: ["Surface the unresolved systems assumption to the people deciding the next action.", "Protect the validated core action and defer the uncertain work with a rationale.", "Move ahead without another field review so the meeting date is preserved."] },
  { id: "communications-newsroom-v1", title: "Communications & newsroom simulation", prefix: "communications", opening: "A student communications team receives conflicting information shortly before publishing a public-facing story. The group must decide what evidence and context belong in the next version.", evidence: "The new information suggests that one source’s perspective may not represent the full situation.", impact: "A teammate asks how the wording and framing could affect the people described in the story.", pressure: "A publication deadline is close, and the team needs a responsible recommendation.", outcome: "The team documents a clearer, better-sourced communication plan and a follow-up question.", work: "story", team: "communications team", evidenceLabel: "source material", stakeholder: "reader and source", openingChoices: ["Review the source material and context before changing the story.", "Invite a teammate to identify who could be affected by the story framing.", "Keep the current publication plan and record the source assumption for later review."], evidenceChoices: ["Verify one key claim with an additional source and compare the context.", "Define a sourcing condition before the team publishes the story.", "Narrow the story scope so the team can protect the most important verified information."], impactChoices: ["Map reader value, source impact, and open questions before recommending a framing.", "Ask an editor or peer outside the team for a short review of the wording.", "State the current publication priority and invite a focused challenge to it."], pressureChoices: ["Surface the unresolved sourcing concern before the publication decision is made.", "Protect the verified core story and defer the uncertain detail with a rationale.", "Publish without another source review so the deadline is preserved."] },
];

export const [engineeringV1Graph, researchV1Graph, policyV1Graph, educationV1Graph, environmentV1Graph, communicationsV1Graph] = specs.map(buildExpandedCareerGraph);
