import type { SimulationGraph } from "../contracts";

export const softwareV1Graph: SimulationGraph = {
  id: "software-systems-v1",
  title: "Software & data delivery simulation",
  startNodeId: "model-alert",
  nodes: {
    "model-alert": { id: "model-alert", title: "A release signal changes", situation: "Two days before a student-facing feature demonstration, a reliability check shows the feature performs unevenly for a group of users. Your team has limited time and needs a next move.", contexts: ["technical", "uncertainty", "time_pressure"], difficulty: 2, decisions: [
      { id: "investigate-data", label: "Inspect the input data and recent changes before proposing a fix.", signals: [{ trait: "analytical_thinking", direction: 1, weight: 2, context: "uncertainty" }, { trait: "attention_to_detail", direction: 1, weight: 1, context: "technical" }], statePatch: { timePressure: 2, discoveredInformation: ["input-distribution-shift"] }, next: "data-audit" },
      { id: "prototype-change", label: "Prototype a targeted technical change and compare it against the current approach.", signals: [{ trait: "problem_solving", direction: 1, weight: 2, context: "technical" }, { trait: "adaptability", direction: 1, weight: 1, context: "uncertainty" }], statePatch: { timePressure: 2, riskExposure: 1 }, next: "latency-tradeoff" },
      { id: "ask-peer", label: "Bring in a teammate for a short, structured review of the evidence.", signals: [{ trait: "collaboration", direction: 1, weight: 2, context: "interpersonal" }, { trait: "communication", direction: 1, weight: 1, context: "uncertainty" }], statePatch: { teamTrust: 1, timePressure: 1 }, next: "peer-review" },
      { id: "ship-current", label: "Keep the current plan and prepare a contingency for the demonstration.", signals: [{ trait: "ownership", direction: 1, weight: 1, context: "time_pressure" }, { trait: "attention_to_detail", direction: -1, weight: 2, context: "technical" }], statePatch: { projectHealth: -2, riskExposure: 2, unresolvedEvents: ["reliability-risk"] }, next: "launch-incident" },
    ] },
    "data-audit": { id: "data-audit", title: "The pattern is not random", situation: "The audit points to a data-distribution change affecting a smaller user group. A quick patch could hide the symptom, but the underlying source is still unclear.", contexts: ["technical", "uncertainty"], difficulty: 2, decisions: [
      { id: "document-and-test", label: "Write down the finding and add a focused test before changing the system.", signals: [{ trait: "attention_to_detail", direction: 1, weight: 2, context: "technical" }, { trait: "long_term_thinking", direction: 1, weight: 1, context: "planning" }], statePatch: { projectHealth: 1 }, next: "fairness-review" },
      { id: "build-isolated-fix", label: "Build a small isolated fix and measure its impact with a comparison run.", signals: [{ trait: "problem_solving", direction: 1, weight: 2, context: "technical" }, { trait: "systems_thinking", direction: 1, weight: 1, context: "uncertainty" }], statePatch: { timePressure: 1 }, next: "scope-tradeoff" },
      { id: "clean-quickly", label: "Apply a quick cleaning rule so the demonstration can proceed.", signals: [{ trait: "adaptability", direction: 1, weight: 1, context: "time_pressure" }, { trait: "ethical_reasoning", direction: -1, weight: 2, context: "ethical" }], statePatch: { riskExposure: 1, projectHealth: -1 }, next: "deadline-call" },
    ] },
    "latency-tradeoff": { id: "latency-tradeoff", title: "A promising change has a cost", situation: "The prototype improves the uneven result, but it slows the experience for everyone. The team needs to decide what evidence to bring to the release discussion.", contexts: ["technical", "resource_constraint", "time_pressure"], difficulty: 2, decisions: [
      { id: "benchmark-options", label: "Benchmark both approaches and compare the user impact before choosing.", signals: [{ trait: "analytical_thinking", direction: 1, weight: 2, context: "technical" }, { trait: "long_term_thinking", direction: 1, weight: 1, context: "planning" }], statePatch: { timePressure: 1, discoveredInformation: ["latency-benchmark"] }, next: "scope-tradeoff" },
      { id: "accept-slower", label: "Recommend the safer but slower version and explain the trade-off to stakeholders.", signals: [{ trait: "ethical_reasoning", direction: 1, weight: 2, context: "ethical" }, { trait: "communication", direction: 1, weight: 1, context: "interpersonal" }], statePatch: { projectHealth: 1 }, next: "stakeholder-review" },
      { id: "revert-for-speed", label: "Revert for speed and schedule investigation after the demonstration.", signals: [{ trait: "adaptability", direction: 1, weight: 1, context: "time_pressure" }, { trait: "long_term_thinking", direction: -1, weight: 2, context: "planning" }], statePatch: { riskExposure: 1 }, next: "deadline-call" },
    ] },
    "peer-review": { id: "peer-review", title: "A teammate sees a missing assumption", situation: "Your teammate notices that the team has been optimizing for a metric that may miss the affected users’ experience. They suggest pausing the demo plan long enough to validate the assumption.", contexts: ["interpersonal", "uncertainty", "ethical"], difficulty: 2, decisions: [
      { id: "integrate-feedback", label: "Integrate the feedback and make the assumption visible to the rest of the team.", signals: [{ trait: "collaboration", direction: 1, weight: 2, context: "interpersonal" }, { trait: "ethical_reasoning", direction: 1, weight: 1, context: "ethical" }], statePatch: { teamTrust: 1 }, next: "fairness-review" },
      { id: "defend-plan", label: "Defend the current metric because the team is close to the deadline.", signals: [{ trait: "ownership", direction: 1, weight: 1, context: "time_pressure" }, { trait: "collaboration", direction: -1, weight: 2, context: "interpersonal" }], statePatch: { teamTrust: -1, timePressure: 1 }, next: "team-conflict" },
      { id: "split-work", label: "Divide the review work so the team can validate the concern without stopping all progress.", signals: [{ trait: "systems_thinking", direction: 1, weight: 2, context: "planning" }, { trait: "collaboration", direction: 1, weight: 1, context: "interpersonal" }], statePatch: { teamTrust: 1, timePressure: 1 }, next: "deadline-call" },
    ] },
    "launch-incident": { id: "launch-incident", title: "The contingency is needed", situation: "During the demonstration, the feature gives an inconsistent result. People are watching, and the team needs to decide how to respond without creating a larger issue.", contexts: ["failure", "time_pressure", "interpersonal"], difficulty: 3, decisions: [
      { id: "communicate-incident", label: "Explain the issue plainly, pause the feature, and coordinate a recovery plan.", signals: [{ trait: "communication", direction: 1, weight: 2, context: "failure" }, { trait: "ownership", direction: 1, weight: 2, context: "interpersonal" }], statePatch: { teamTrust: 1, projectHealth: -1 }, next: "team-conflict" },
      { id: "rollback-safely", label: "Roll back to the known-safe version and document what triggered the failure.", signals: [{ trait: "attention_to_detail", direction: 1, weight: 2, context: "failure" }, { trait: "long_term_thinking", direction: 1, weight: 1, context: "planning" }], statePatch: { projectHealth: 1, riskExposure: -1 }, next: "scope-tradeoff" },
      { id: "patch-live", label: "Attempt a live patch while the demonstration continues.", signals: [{ trait: "adaptability", direction: 1, weight: 1, context: "failure" }, { trait: "long_term_thinking", direction: -1, weight: 2, context: "time_pressure" }], statePatch: { riskExposure: 2, projectHealth: -1 }, next: "deadline-call" },
    ] },
    "fairness-review": { id: "fairness-review", title: "The impact needs a decision", situation: "The validation confirms that a smaller user group experiences weaker results. The issue is measurable, but the team has not agreed on what a responsible release looks like.", contexts: ["ethical", "technical", "interpersonal"], difficulty: 3, decisions: [
      { id: "pause-and-analyze", label: "Pause the affected path, analyze the cause, and define a fair release condition.", signals: [{ trait: "ethical_reasoning", direction: 1, weight: 3, context: "ethical" }, { trait: "analytical_thinking", direction: 1, weight: 1, context: "technical" }], statePatch: { projectHealth: 1, timePressure: 1 }, next: "scope-tradeoff" },
      { id: "add-monitoring", label: "Release with explicit monitoring and a short deadline for a targeted improvement.", signals: [{ trait: "systems_thinking", direction: 1, weight: 2, context: "planning" }, { trait: "ethical_reasoning", direction: 1, weight: 1, context: "ethical" }], statePatch: { riskExposure: 1 }, next: "scope-tradeoff" },
      { id: "minimize-difference", label: "Treat the difference as too small to change the release plan.", signals: [{ trait: "ethical_reasoning", direction: -1, weight: 3, context: "ethical" }, { trait: "attention_to_detail", direction: -1, weight: 1, context: "technical" }], statePatch: { riskExposure: 2, teamTrust: -1 }, next: "deadline-call" },
    ] },
    "scope-tradeoff": { id: "scope-tradeoff", title: "The plan has more work than time", situation: "The evidence points to several improvements, but the team can complete only one before the release window. The choice will shape both near-term quality and what the team learns next.", contexts: ["resource_constraint", "planning", "technical"], difficulty: 2, decisions: [
      { id: "protect-validation", label: "Prioritize validation and defer a visible enhancement with a documented rationale.", signals: [{ trait: "long_term_thinking", direction: 1, weight: 2, context: "planning" }, { trait: "attention_to_detail", direction: 1, weight: 1, context: "resource_constraint" }], statePatch: { projectHealth: 1 }, next: "resource-budget" },
      { id: "shorten-scope", label: "Reduce feature scope so the team can deliver a reliable smaller version.", signals: [{ trait: "adaptability", direction: 1, weight: 2, context: "resource_constraint" }, { trait: "ownership", direction: 1, weight: 1, context: "planning" }], statePatch: { projectHealth: 1 }, next: "deadline-call" },
      { id: "reframe-priorities", label: "Bring product and engineering together to re-prioritize against the evidence.", signals: [{ trait: "communication", direction: 1, weight: 2, context: "interpersonal" }, { trait: "systems_thinking", direction: 1, weight: 1, context: "planning" }], statePatch: { teamTrust: 1 }, next: "team-conflict" },
    ] },
    "team-conflict": { id: "team-conflict", title: "The team has different risk thresholds", situation: "A teammate feels the current approach is too risky, while another wants to move quickly. The conversation is becoming less productive as the deadline approaches.", contexts: ["interpersonal", "time_pressure", "uncertainty"], difficulty: 2, decisions: [
      { id: "listen-and-map", label: "Ask each person to name their concern, then map the evidence and open questions together.", signals: [{ trait: "collaboration", direction: 1, weight: 2, context: "interpersonal" }, { trait: "communication", direction: 1, weight: 1, context: "uncertainty" }], statePatch: { teamTrust: 2 }, next: "deadline-call" },
      { id: "assert-direction", label: "Choose a direction quickly and ask the team to execute it.", signals: [{ trait: "ownership", direction: 1, weight: 1, context: "time_pressure" }, { trait: "collaboration", direction: -1, weight: 2, context: "interpersonal" }], statePatch: { teamTrust: -1 }, next: "deadline-call" },
      { id: "facilitate-evidence", label: "Set a short decision window and agree on the evidence that will determine the choice.", signals: [{ trait: "systems_thinking", direction: 1, weight: 2, context: "planning" }, { trait: "communication", direction: 1, weight: 1, context: "interpersonal" }], statePatch: { teamTrust: 1 }, next: "deadline-call" },
    ] },
    "deadline-call": { id: "deadline-call", title: "A deadline is now a risk decision", situation: "The release time is close. You have enough information to know there is a trade-off, but not enough to remove all uncertainty.", contexts: ["time_pressure", "uncertainty", "planning"], difficulty: 3, decisions: [
      { id: "surface-risk", label: "Surface the risk, share options, and ask for a decision with the people accountable for the release.", signals: [{ trait: "communication", direction: 1, weight: 2, context: "time_pressure" }, { trait: "ownership", direction: 1, weight: 1, context: "planning" }], statePatch: { teamTrust: 1 }, next: "resource-budget" },
      { id: "cut-testing", label: "Cut the remaining testing to preserve the delivery date.", signals: [{ trait: "attention_to_detail", direction: -1, weight: 2, context: "time_pressure" }, { trait: "long_term_thinking", direction: -1, weight: 1, context: "planning" }], statePatch: { riskExposure: 2, projectHealth: -1 }, next: "resource-budget" },
      { id: "protect-core", label: "Protect the validated core path and clearly defer the unvalidated work.", signals: [{ trait: "attention_to_detail", direction: 1, weight: 2, context: "technical" }, { trait: "adaptability", direction: 1, weight: 1, context: "time_pressure" }], statePatch: { projectHealth: 1 }, next: "stakeholder-review" },
    ] },
    "resource-budget": { id: "resource-budget", title: "Resources force a trade-off", situation: "The team can fund only one next step: a deeper experiment, a monitoring improvement, or a manual support process. Each protects a different kind of outcome.", contexts: ["resource_constraint", "planning", "ethical"], difficulty: 2, decisions: [
      { id: "run-experiment", label: "Run the lowest-cost experiment that would change the next decision.", signals: [{ trait: "analytical_thinking", direction: 1, weight: 2, context: "resource_constraint" }, { trait: "long_term_thinking", direction: 1, weight: 1, context: "planning" }], statePatch: { discoveredInformation: ["decision-changing-experiment"] }, next: "stakeholder-review" },
      { id: "improve-monitoring", label: "Invest in monitoring so the team can detect and respond to impact quickly.", signals: [{ trait: "systems_thinking", direction: 1, weight: 2, context: "technical" }, { trait: "ethical_reasoning", direction: 1, weight: 1, context: "ethical" }], statePatch: { riskExposure: -1 }, next: "implementation-plan" },
      { id: "manual-support", label: "Provide a temporary manual support path for affected users while the technical work continues.", signals: [{ trait: "ethical_reasoning", direction: 1, weight: 2, context: "ethical" }, { trait: "communication", direction: 1, weight: 1, context: "interpersonal" }], statePatch: { teamTrust: 1, projectHealth: 1 }, next: "implementation-plan" },
    ] },
    "stakeholder-review": { id: "stakeholder-review", title: "You are ready to recommend a path", situation: "You have enough evidence to brief the people responsible for the outcome. The value now is making the trade-offs clear and leaving a learning path after the immediate decision.", contexts: ["interpersonal", "planning", "execution"], difficulty: 3, decisions: [
      { id: "present-options", label: "Present options with evidence, consequences, and a recommendation.", signals: [{ trait: "communication", direction: 1, weight: 2, context: "planning" }, { trait: "systems_thinking", direction: 1, weight: 1, context: "execution" }], statePatch: { teamTrust: 1 }, next: "reflection" },
      { id: "promise-certainty", label: "Promise the strongest outcome so the team can move forward quickly.", signals: [{ trait: "ownership", direction: 1, weight: 1, context: "time_pressure" }, { trait: "communication", direction: -1, weight: 2, context: "uncertainty" }], statePatch: { riskExposure: 1 }, next: "reflection" },
      { id: "name-uncertainty", label: "Name what is still uncertain and recommend a staged decision with review points.", signals: [{ trait: "ethical_reasoning", direction: 1, weight: 1, context: "uncertainty" }, { trait: "long_term_thinking", direction: 1, weight: 2, context: "planning" }], statePatch: { projectHealth: 1 }, next: "reflection" },
    ] },
    "implementation-plan": { id: "implementation-plan", title: "Turn the choice into an implementation plan", situation: "The immediate priority is clearer. Now the team needs a plan that makes ownership, validation, and communication visible before the next release review.", contexts: ["planning", "execution", "interpersonal"], difficulty: 2, decisions: [
      { id: "assign-review-points", label: "Define owners, review points, and a measurable condition for moving forward.", signals: [{ trait: "ownership", direction: 1, weight: 2, context: "planning" }, { trait: "attention_to_detail", direction: 1, weight: 1, context: "execution" }], statePatch: { projectHealth: 1 }, next: "stakeholder-review" },
      { id: "coordinate-team", label: "Coordinate the work with the team and make dependencies explicit.", signals: [{ trait: "collaboration", direction: 1, weight: 2, context: "interpersonal" }, { trait: "systems_thinking", direction: 1, weight: 1, context: "planning" }], statePatch: { teamTrust: 1 }, next: "stakeholder-review" },
      { id: "act-independently", label: "Start the most urgent technical work independently and update others later.", signals: [{ trait: "ownership", direction: 1, weight: 1, context: "execution" }, { trait: "communication", direction: -1, weight: 1, context: "interpersonal" }], statePatch: { teamTrust: -1 }, next: "stakeholder-review" },
    ] },
    reflection: { id: "reflection", title: "The release decision is documented", situation: "The team has a path forward. Before closing the loop, there is an opportunity to capture what should change in the way the team handles a similar decision next time.", contexts: ["failure", "planning", "interpersonal"], difficulty: 2, decisions: [
      { id: "capture-learning", label: "Capture the evidence, decision rationale, and a learning question for the next iteration.", signals: [{ trait: "long_term_thinking", direction: 1, weight: 2, context: "planning" }, { trait: "analytical_thinking", direction: 1, weight: 1, context: "failure" }], statePatch: { projectHealth: 1 }, next: "learning-plan" },
      { id: "thank-team", label: "Recognize the team’s contribution and agree on a short follow-up conversation.", signals: [{ trait: "collaboration", direction: 1, weight: 1, context: "interpersonal" }, { trait: "communication", direction: 1, weight: 1, context: "planning" }], statePatch: { teamTrust: 1 }, next: "learning-plan" },
      { id: "move-on", label: "Move on quickly so attention can return to the next urgent task.", signals: [{ trait: "adaptability", direction: 1, weight: 1, context: "time_pressure" }, { trait: "long_term_thinking", direction: -1, weight: 1, context: "planning" }], statePatch: { unresolvedEvents: ["post-release-learning"] }, next: "learning-plan" },
    ] },
    "learning-plan": { id: "learning-plan", title: "Choose a next learning move", situation: "The simulation is nearly complete. One final choice will determine what evidence the team carries into its next project.", contexts: ["planning", "execution"], difficulty: 2, decisions: [
      { id: "practice-skill", label: "Choose one skill to practice through a small, evidence-focused project.", signals: [{ trait: "ownership", direction: 1, weight: 1, context: "execution" }, { trait: "long_term_thinking", direction: 1, weight: 1, context: "planning" }], next: "debrief" },
      { id: "seek-feedback", label: "Ask for feedback on how you communicated the trade-off and acted on evidence.", signals: [{ trait: "communication", direction: 1, weight: 1, context: "interpersonal" }, { trait: "adaptability", direction: 1, weight: 1, context: "planning" }], next: "debrief" },
      { id: "review-outcome", label: "Plan a structured review of the outcome before deciding what to change.", signals: [{ trait: "analytical_thinking", direction: 1, weight: 1, context: "planning" }, { trait: "attention_to_detail", direction: 1, weight: 1, context: "execution" }], next: "debrief" },
    ] },
    debrief: { id: "debrief", title: "Simulation complete", situation: "Your decisions have created a distinct path through the situation. PathPilot can now summarize the patterns it observed in this simulation.", contexts: ["planning"], difficulty: 1, decisions: [], terminal: true },
  },
};
